### ISSUE TITLE
Investigate exception message during run test case TaskExecutorThreadTest

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1198]
When run all test case `TaskExecutorThreadTest`, the exception will occur, error message is:

```
[ERROR] 2020-07-20 19:59:41,631 --test_job@-@0@-@READY@-@fake_slave_id@-@0_Worker-1-- [org.quartz.core.JobRunShell] Job DEFAULT.test_job threw an unhandled Exception:  
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
	at com.google.common.util.concurrent.MoreExecutors$Application.addShutdownHook(MoreExecutors.java:285)
	at com.google.common.util.concurrent.MoreExecutors$Application.addDelayedShutdownHook(MoreExecutors.java:262)
	at com.google.common.util.concurrent.MoreExecutors$Application.getExitingExecutorService(MoreExecutors.java:237)
	at com.google.common.util.concurrent.MoreExecutors$Application.getExitingExecutorService(MoreExecutors.java:242)
	at com.google.common.util.concurrent.MoreExecutors.getExitingExecutorService(MoreExecutors.java:126)
	at org.apache.shardingsphere.elasticjob.infra.concurrent.ElasticJobExecutorService.createExecutorService(ElasticJobExecutorService.java:51)
	at org.apache.shardingsphere.elasticjob.infra.handler.threadpool.impl.AbstractJobExecutorServiceHandler.createExecutorService(AbstractJobExecutorServiceHandler.java:32)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.<init>(ElasticJobExecutor.java:75)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.<init>(ElasticJobExecutor.java:63)
	at org.apache.shardingsphere.elasticjob.cloud.executor.prod.DaemonTaskScheduler$DaemonJob.createJobExecutor(DaemonTaskScheduler.java:197)
	at org.apache.shardingsphere.elasticjob.cloud.executor.prod.DaemonTaskScheduler$DaemonJob.getJobExecutor(DaemonTaskScheduler.java:186)
	at org.apache.shardingsphere.elasticjob.cloud.executor.prod.DaemonTaskScheduler$DaemonJob.execute(DaemonTaskScheduler.java:178)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
[ERROR] 2020-07-20 19:59:41,636 --test_job@-@0@-@READY@-@fake_slave_id@-@0_Worker-1-- [org.quartz.core.ErrorLogger] Job (DEFAULT.test_job threw an exception. 
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
	at com.google.common.util.concurrent.MoreExecutors$Application.addShutdownHook(MoreExecutors.java:285)
	at com.google.common.util.concurrent.MoreExecutors$Application.addDelayedShutdownHook(MoreExecutors.java:262)
	at com.google.common.util.concurrent.MoreExecutors$Application.getExitingExecutorService(MoreExecutors.java:237)
	at com.google.common.util.concurrent.MoreExecutors$Application.getExitingExecutorService(MoreExecutors.java:242)
	at com.google.common.util.concurrent.MoreExecutors.getExitingExecutorService(MoreExecutors.java:126)
	at org.apache.shardingsphere.elasticjob.infra.concurrent.ElasticJobExecutorService.createExecutorService(ElasticJobExecutorService.java:51)
	at org.apache.shardingsphere.elasticjob.infra.handler.threadpool.impl.AbstractJobExecutorServiceHandler.createExecutorService(AbstractJobExecutorServiceHandler.java:32)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.<init>(ElasticJobExecutor.java:75)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.<init>(ElasticJobExecutor.java:63)
	at org.apache.shardingsphere.elasticjob.cloud.executor.prod.DaemonTaskScheduler$DaemonJob.createJobExecutor(DaemonTaskScheduler.java:197)
	at org.apache.shardingsphere.elasticjob.cloud.executor.prod.DaemonTaskScheduler$DaemonJob.getJobExecutor(DaemonTaskScheduler.java:186)
	at org.apache.shardingsphere.elasticjob.cloud.executor.prod.DaemonTaskScheduler$DaemonJob.execute(DaemonTaskScheduler.java:178)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
```

Please investigate the reason.

**Comment by jiang2015** [comment]
please assign to me，thanks
