### ISSUE TITLE
zookeeper not support 3.5.x version

### ISSUE THREAD

**Issue by miaogr86** [apache/shardingsphere-elasticjob#1265]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elastic-job-lite/issues).
- Read documentation: [ElasticJob Doc](http://shardingsphere.apache.org/elasticjob/docs/elastic-job-lite/00-overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ElasticJob did you use?
3.0.0-alpha-SNAPSHOT

### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite

### Actual behavior
**error logs：**
2020-07-23 23:38:55.205  WARN 444 --- [.34.4.126:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x1057e61ccae0000 for sever 10.34.4.126/10.34.4.126:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.

java.io.IOException: Xid out of order. Got Xid 88 with err -6 expected Xid 87 for a packet with details: clientPath:null serverPath:null finished:false header:: 87,14  replyHeader:: 0,0,-4  request:: org.apache.zookeeper.MultiOperationRecord@ff58e5c1 response:: org.apache.zookeeper.MultiResponse@0
	at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:938)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:96)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:348)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1262)

2020-07-23 23:38:55.306  WARN 444 --- [ain-EventThread] o.a.c.retry.ExponentialBackoffRetry      : Sleep extension too large (6000). Pinning to 3000
2020-07-23 23:38:55.306  WARN 444 --- [ain-EventThread] o.a.c.retry.ExponentialBackoffRetry      : Sleep extension too large (5000). Pinning to 3000
2020-07-23 23:38:55.306  INFO 444 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : State change: SUSPENDED
2020-07-23 23:38:56.688  INFO 444 --- [.34.4.126:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 10.34.4.126/10.34.4.126:2181.
2020-07-23 23:38:56.689  INFO 444 --- [.34.4.126:2181)] org.apache.zookeeper.ClientCnxn          : SASL config status: Will not attempt to authenticate using SASL (unknown error)
2020-07-23 23:38:56.693  INFO 444 --- [.34.4.126:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established, initiating session, client: /10.243.19.182:61828, server: 10.34.4.126/10.34.4.126:2181
2020-07-23 23:38:56.699  INFO 444 --- [.34.4.126:2181)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server 10.34.4.126/10.34.4.126:2181, session id = 0x1057e61ccae0000, negotiated timeout = 40000
2020-07-23 23:38:56.699  INFO 444 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : State change: RECONNECTED
2020-07-23 23:38:56.699  WARN 444 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : ConnectionStateManager queue full - dropping events to make room
2020-07-23 23:38:56.709  WARN 444 --- [.34.4.126:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x1057e61ccae0000 for sever 10.34.4.126/10.34.4.126:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.

org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x1057e61ccae0000, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:348)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1262)

2020-07-23 23:38:56.810  INFO 444 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : State change: SUSPENDED
2020-07-23 23:38:56.810  WARN 444 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : ConnectionStateManager queue full - dropping events to make room
2020-07-23 23:38:58.719  INFO 444 --- [.34.4.126:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 10.34.4.126/10.34.4.126:2181.
2020-07-23 23:38:58.720  INFO 444 --- [.34.4.126:2181)] org.apache.zookeeper.ClientCnxn          : SASL config status: Will not attempt to authenticate using SASL (unknown error)
2020-07-23 23:38:58.724  INFO 444 --- [.34.4.126:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established, initiating session, client: /10.243.19.182:61830, server: 10.34.4.126/10.34.4.126:2181
2020-07-23 23:38:58.729  INFO 444 --- [.34.4.126:2181)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server 10.34.4.126/10.34.4.126:2181, session id = 0x1057e61ccae0000, negotiated timeout = 40000
2020-07-23 23:38:58.729  INFO 444 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : State change: RECONNECTED
2020-07-23 23:38:58.729  WARN 444 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : ConnectionStateManager queue full - dropping events to make room
2020-07-23 23:38:58.734  WARN 444 --- [.34.4.126:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x1057e61ccae0000 for sever 10.34.4.126/10.34.4.126:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.

java.io.IOException: Xid out of order. Got Xid 95 with err -6 expected Xid 94 for a packet with details: clientPath:null serverPath:null finished:false header:: 94,14  replyHeader:: 0,0,-4  request:: org.apache.zookeeper.MultiOperationRecord@ff58e5c1 response:: org.apache.zookeeper.MultiResponse@0
	at org.apache.zookeeper.ClientCnxn$SendThread.readResponse(ClientCnxn.java:938)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:96)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:348)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1262)

2020-07-23 23:38:58.836  INFO 444 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : State change: SUSPENDED
2020-07-23 23:38:58.837  WARN 444 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : ConnectionStateManager queue full - dropping events to make room
2020-07-23 23:38:58.837 ERROR 444 --- [ain-EventThread] o.a.c.f.imps.CuratorFrameworkImpl        : Background operation retry gave up

org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:851)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:643)
	at org.apache.curator.framework.imps.AddWatchBuilderImpl.lambda$performBackgroundOperation$1(AddWatchBuilderImpl.java:166)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:722)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:551)

2020-07-23 23:38:58.843 ERROR 444 --- [ain-EventThread] o.a.c.f.imps.CuratorFrameworkImpl        : Background operation retry gave up

org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkBackgroundRetry(CuratorFrameworkImpl.java:851)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:643)
	at org.apache.curator.framework.imps.AddWatchBuilderImpl.lambda$performBackgroundOperation$1(AddWatchBuilderImpl.java:166)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:722)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:551)

### Steps to reproduce the behavior.
**zookeeper server use V3.5.8**

**Comment by terrymanu** [comment]
ZooKeeper 3.6.0 or above required.
FYI: https://github.com/apache/shardingsphere-elasticjob/blob/master/README.md
