### ISSUE TITLE
Elastic job console registry configuration connection is always loading?  The zookeeper address is right, and the namespace is right

### ISSUE THREAD

**Issue by kakagit** [apache/shardingsphere-elasticjob#1317]
Elastic job console registry configuration connection is always loading?

The zookeeper address is right, and the namespace is right

**Comment by Technoboy-** [comment]
Did you use the latest version of [elastic job console?](https://github.com/apache/shardingsphere-elasticjob-ui)
If so, please @menghaoranss take a look.
If not, could you please try with zkCli to test if the config is right.  If the issue still existed, please paste a pic, thanks.

**Comment by kakagit** [comment]
Elastic job console version is 2.1.5, and my listening service is running normally
![IMG20200803-143414](https://user-images.githubusercontent.com/33457721/89155405-5622f480-d59b-11ea-8f5d-7e54582fd960.jpeg)
![Meixin20200803143617](https://user-images.githubusercontent.com/33457721/89155420-5e7b2f80-d59b-11ea-8e54-37a976f7d542.png)

**Comment by Technoboy-** [comment]
Ok. please inspect the page and turn to network, refresh the page to check why it's loading.  I think it's simple for you to resolve it.

**Comment by kakagit** [comment]
![Uploading Meixin20200803143617.png…]()

**Comment by kakagit** [comment]
java.lang.NoClassDefFoundError: org/apache/zookeeper/KeeperException$OperationTimeoutException
	at com.dangdang.ddframe.job.lite.lifecycle.internal.reg.RegistryCenterFactory.createCoordinatorRegistryCenter(RegistryCenterFactory.java:65)
	at com.dangdang.ddframe.job.lite.console.restful.config.RegistryCenterRestfulApi.setRegistryCenterNameToSession(RegistryCenterRestfulApi.java:118)
	at com.dangdang.ddframe.job.lite.console.restful.config.RegistryCenterRestfulApi.connect(RegistryCenterRestfulApi.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:427)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:984)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1045)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:236)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.KeeperException$OperationTimeoutException

**Comment by kakagit** [comment]
There is a problem with the zookeeper jar package dependency when packaging
