### ISSUE TITLE
The example of spring boot start can not run

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#1319]
When running the example `SpringBootMain` in module elasticjob-example-lite-springboot,  exception occur:

```
[WARN ] 2020-08-03 12:53:55,673 --main-- [org.springframework.boot.context.event.EventPublishingRunListener] Error calling ApplicationEventListener 
java.lang.NoSuchMethodError: ch.qos.logback.classic.LoggerContext.removeObject(Ljava/lang/String;)V
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.markAsUninitialized(LogbackLoggingSystem.java:318) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.cleanUp(LogbackLoggingSystem.java:212) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationFailedEvent(LoggingApplicationListener.java:263) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:226) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:158) [spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) [spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.failed(EventPublishingRunListener.java:130) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.callFailedListener(SpringApplicationRunListeners.java:90) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.failed(SpringApplicationRunListeners.java:83) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:808) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.apache.shardingsphere.elasticjob.lite.example.SpringBootMain.main(SpringBootMain.java:30) [classes/:na]
[INFO ] 2020-08-03 12:53:55,700 --main-- [org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener] 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
[ERROR] 2020-08-03 12:53:55,717 --main-- [org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter] 

***************************
APPLICATION FAILED TO START
***************************

Description:

Web server failed to start. Port 8080 was already in use.

Action:

Identify and stop the process that's listening on port 8080 or configure this application to listen on another port.
 
[INFO ] 2020-08-03 12:54:09,096 --Quartz Shutdown-Hook dataflowJob-- [org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobShutdownHookPlugin] Shutting down Quartz... dataflowJob 
[INFO ] 2020-08-03 12:54:09,097 --Quartz Shutdown-Hook simpleJob-- [org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobShutdownHookPlugin] Shutting down Quartz... simpleJob 
[INFO ] 2020-08-03 12:54:09,099 --Quartz Shutdown-Hook manualScriptJob-- [org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobShutdownHookPlugin] Shutting down Quartz... manualScriptJob 
[INFO ] 2020-08-03 12:54:09,099 --Quartz Shutdown-Hook simpleJob-- [org.quartz.core.QuartzScheduler] Scheduler simpleJob_$_NON_CLUSTERED shutting down. 
[INFO ] 2020-08-03 12:54:09,099 --Quartz Shutdown-Hook dataflowJob-- [org.quartz.core.QuartzScheduler] Scheduler dataflowJob_$_NON_CLUSTERED shutting down. 
[INFO ] 2020-08-03 12:54:09,099 --Quartz Shutdown-Hook manualScriptJob-- [org.quartz.core.QuartzScheduler] Scheduler manualScriptJob_$_NON_CLUSTERED shutting down. 
[INFO ] 2020-08-03 12:54:09,099 --Quartz Shutdown-Hook scriptJob-- [org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobShutdownHookPlugin] Shutting down Quartz... scriptJob 
[INFO ] 2020-08-03 12:54:09,100 --Quartz Shutdown-Hook simpleJob-- [org.quartz.core.QuartzScheduler] Scheduler simpleJob_$_NON_CLUSTERED paused. 
[INFO ] 2020-08-03 12:54:09,100 --Quartz Shutdown-Hook dataflowJob-- [org.quartz.core.QuartzScheduler] Scheduler dataflowJob_$_NON_CLUSTERED paused. 
[INFO ] 2020-08-03 12:54:09,100 --Quartz Shutdown-Hook manualScriptJob-- [org.quartz.core.QuartzScheduler] Scheduler manualScriptJob_$_NON_CLUSTERED paused. 
[INFO ] 2020-08-03 12:54:09,100 --Quartz Shutdown-Hook scriptJob-- [org.quartz.core.QuartzScheduler] Scheduler scriptJob_$_NON_CLUSTERED shutting down. 
[INFO ] 2020-08-03 12:54:09,101 --Quartz Shutdown-Hook scriptJob-- [org.quartz.core.QuartzScheduler] Scheduler scriptJob_$_NON_CLUSTERED paused. 
[ERROR] 2020-08-03 12:54:09,249 --Quartz Shutdown-Hook dataflowJob-- [org.apache.zookeeper.server.NIOServerCnxnFactory] Thread Thread[Quartz Shutdown-Hook dataflowJob,5,main] died 
org.apache.shardingsphere.elasticjob.reg.exception.RegException: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.shardingsphere.elasticjob.reg.exception.RegExceptionHandler.handleException(RegExceptionHandler.java:48) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:162) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:143) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:77) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.election.LeaderService.isLeader(LeaderService.java:82) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobShutdownHookPlugin.shutdown(JobShutdownHookPlugin.java:68) ~[classes/:na]
	at org.quartz.core.QuartzScheduler.shutdownPlugins(QuartzScheduler.java:2381) ~[quartz-2.3.2.jar:na]
	at org.quartz.core.QuartzScheduler.shutdown(QuartzScheduler.java:730) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.StdScheduler.shutdown(StdScheduler.java:206) ~[quartz-2.3.2.jar:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobScheduleController.shutdown(JobScheduleController.java:166) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobShutdownHookPlugin$1.run(JobShutdownHookPlugin.java:82) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:823) ~[curator-client-5.1.0.jar:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:423) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:457) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:158) ~[classes/:na]
	... 9 common frames omitted
[ERROR] 2020-08-03 12:54:09,349 --Quartz Shutdown-Hook scriptJob-- [org.apache.zookeeper.server.NIOServerCnxnFactory] Thread Thread[Quartz Shutdown-Hook scriptJob,5,main] died 
org.apache.shardingsphere.elasticjob.reg.exception.RegException: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.shardingsphere.elasticjob.reg.exception.RegExceptionHandler.handleException(RegExceptionHandler.java:48) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:162) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:143) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:77) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.election.LeaderService.isLeader(LeaderService.java:82) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobShutdownHookPlugin.shutdown(JobShutdownHookPlugin.java:68) ~[classes/:na]
	at org.quartz.core.QuartzScheduler.shutdownPlugins(QuartzScheduler.java:2381) ~[quartz-2.3.2.jar:na]
	at org.quartz.core.QuartzScheduler.shutdown(QuartzScheduler.java:730) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.StdScheduler.shutdown(StdScheduler.java:206) ~[quartz-2.3.2.jar:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobScheduleController.shutdown(JobScheduleController.java:166) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobShutdownHookPlugin$1.run(JobShutdownHookPlugin.java:82) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:823) ~[curator-client-5.1.0.jar:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:423) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:457) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:158) ~[classes/:na]
	... 9 common frames omitted
[ERROR] 2020-08-03 12:54:09,540 --Quartz Shutdown-Hook manualScriptJob-- [org.apache.zookeeper.server.NIOServerCnxnFactory] Thread Thread[Quartz Shutdown-Hook manualScriptJob,5,main] died 
org.apache.shardingsphere.elasticjob.reg.exception.RegException: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.shardingsphere.elasticjob.reg.exception.RegExceptionHandler.handleException(RegExceptionHandler.java:48) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:162) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:143) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:77) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.election.LeaderService.isLeader(LeaderService.java:82) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobShutdownHookPlugin.shutdown(JobShutdownHookPlugin.java:68) ~[classes/:na]
	at org.quartz.core.QuartzScheduler.shutdownPlugins(QuartzScheduler.java:2381) ~[quartz-2.3.2.jar:na]
	at org.quartz.core.QuartzScheduler.shutdown(QuartzScheduler.java:730) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.StdScheduler.shutdown(StdScheduler.java:206) ~[quartz-2.3.2.jar:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobScheduleController.shutdown(JobScheduleController.java:166) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobShutdownHookPlugin$1.run(JobShutdownHookPlugin.java:82) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:823) ~[curator-client-5.1.0.jar:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:423) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:457) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:158) ~[classes/:na]
	... 9 common frames omitted
[ERROR] 2020-08-03 12:54:09,602 --Quartz Shutdown-Hook simpleJob-- [org.apache.zookeeper.server.NIOServerCnxnFactory] Thread Thread[Quartz Shutdown-Hook simpleJob,5,main] died 
org.apache.shardingsphere.elasticjob.reg.exception.RegException: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.shardingsphere.elasticjob.reg.exception.RegExceptionHandler.handleException(RegExceptionHandler.java:48) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:162) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:143) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:77) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.election.LeaderService.isLeader(LeaderService.java:82) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobShutdownHookPlugin.shutdown(JobShutdownHookPlugin.java:68) ~[classes/:na]
	at org.quartz.core.QuartzScheduler.shutdownPlugins(QuartzScheduler.java:2381) ~[quartz-2.3.2.jar:na]
	at org.quartz.core.QuartzScheduler.shutdown(QuartzScheduler.java:730) ~[quartz-2.3.2.jar:na]
	at org.quartz.impl.StdScheduler.shutdown(StdScheduler.java:206) ~[quartz-2.3.2.jar:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobScheduleController.shutdown(JobScheduleController.java:166) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobShutdownHookPlugin$1.run(JobShutdownHookPlugin.java:82) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:823) ~[curator-client-5.1.0.jar:na]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:423) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:457) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:158) ~[classes/:na]
	... 9 common frames omitted
```

**Comment by TeslaCN** [comment]
The port 8080 has already in use. please specify another port or stop the application using 8080.
