### ISSUE TITLE
job cant not run 

### ISSUE THREAD

**Issue by zhouyutaoz** [apache/shardingsphere-elasticjob#1434]
## Question

[2020-09-03 14:28:45,017] [ERROR] o.a.c.framework.recipes.cache.TreeCache 751 [Curator-TreeCache-61] traceLogId:[] dstTraceId:[] TxId:[] [TreeCache] [handleException] 
java.lang.NullPointerException: null
        at com.dangdang.ddframe.job.lite.internal.instance.InstanceNode.isLocalInstancePath(InstanceNode.java:66)
        at com.dangdang.ddframe.job.lite.internal.instance.TriggerListenerManager$JobTriggerStatusJobListener.dataChanged(TriggerListenerManager.java:55)
        at com.dangdang.ddframe.job.lite.internal.listener.AbstractJobListener.childEvent(AbstractJobListener.java:44)
        at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:732)
        at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:726)
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85)
        at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:725)
        at org.apache.curator.framework.recipes.cache.TreeCache.access$1400(TreeCache.java:71)
        at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:843)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
失效转移后，定时任务不可以运行，手动触发后也没有反应，看日志有这个异常打印

**Comment by Technoboy-** [comment]
Hi, from the stack trace log, you're using an older version of ElasticJob that not in our maintaining. Could you upgrade to newest version and try our new features?
