### ISSUE TITLE
The current error-handler-email module's testcases are too slow

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere-elasticjob#1504]
## Question

The error-handler-email module's testcases call the real 'Transport.send()' method even if they aren't actually send any valid email. Each testcase which is going to invoke 'Transport.send()' will take about 2 minutes on socket operation.
```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:-1)
	  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
	  - locked <0xa02> (a java.net.SocksSocketImpl)
	  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
	  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
	  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
	  at java.net.Socket.connect(Socket.java:606)
	  at java.net.Socket.connect(Socket.java:555)
	  at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:352)
	  at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
	  at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2160)
	  at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:726)
	  - locked <0xa03> (a com.sun.mail.smtp.SMTPTransport)
	  at javax.mail.Service.connect(Service.java:388)
	  at javax.mail.Service.connect(Service.java:246)
	  at javax.mail.Service.connect(Service.java:195)
	  at javax.mail.Transport.send0(Transport.java:254)
	  at javax.mail.Transport.send(Transport.java:124)
	  at org.apache.shardingsphere.elasticjob.error.handler.email.EmailJobErrorHandler.sendMessage(EmailJobErrorHandler.java:127)
	  at org.apache.shardingsphere.elasticjob.error.handler.email.EmailJobErrorHandler.handleException(EmailJobErrorHandler.java:64)
	  at org.apache.shardingsphere.elasticjob.error.handler.email.EmailJobErrorHandlerTest.assertHandleExceptionWithYAMLConfiguration(EmailJobErrorHandlerTest.java:45)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	  at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:68)
	  at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:74)
	  at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
	  at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:161)
	  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	  at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	  at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	  at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	  at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

**Comment by TeslaCN** [comment]
Close due to refactor. Ref #1517
