### ISSUE TITLE
Introduce elasticjob-error-handler-email without use will cause error

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere-elasticjob#1509]
### Which version of ElasticJob did you use?
3.0.0-beta-SNAPSHOT
### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
ElasticJob-Lite
### Actual behavior
```
Exception in thread "main" java.util.ServiceConfigurationError: org.apache.shardingsphere.elasticjob.error.handler.JobErrorHandler: Provider org.apache.shardingsphere.elasticjob.error.handler.email.EmailJobErrorHandler could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at org.apache.shardingsphere.elasticjob.error.handler.JobErrorHandlerFactory.<clinit>(JobErrorHandlerFactory.java:40)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.<init>(ElasticJobExecutor.java:76)
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.<init>(ElasticJobExecutor.java:63)
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobScheduler.<init>(JobScheduler.java:86)
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobScheduler.<init>(JobScheduler.java:75)
	at org.apache.shardingsphere.elasticjob.lite.api.bootstrap.impl.ScheduleJobBootstrap.<init>(ScheduleJobBootstrap.java:37)
	at icu.wwj.project.hello.elasticjob.HelloElasticjob.main(HelloElasticjob.java:19)
Caused by: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "xxx"
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:249)
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:239)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	at com.google.gson.Gson.fromJson(Gson.java:844)
	at com.google.gson.Gson.fromJson(Gson.java:793)
	at com.google.gson.Gson.fromJson(Gson.java:765)
	at org.apache.shardingsphere.elasticjob.infra.yaml.YamlEngine.unmarshal(YamlEngine.java:82)
	at org.apache.shardingsphere.elasticjob.error.handler.email.ConfigurationLoader.buildConfigByYaml(ConfigurationLoader.java:43)
	at org.apache.shardingsphere.elasticjob.error.handler.email.EmailJobErrorHandler.loadConfiguration(EmailJobErrorHandler.java:74)
	at org.apache.shardingsphere.elasticjob.error.handler.email.EmailJobErrorHandler.<init>(EmailJobErrorHandler.java:56)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	... 9 more
Caused by: java.lang.NumberFormatException: For input string: "xxx"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:543)
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1198)
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:247)
	... 25 more
Disconnected from the target VM, address: '127.0.0.1:34725', transport: 'socket'

Process finished with exit code 1
```

**Comment by TeslaCN** [comment]
Close due to refactor.
