### ISSUE TITLE
elastic job start error

### ISSUE THREAD

**Issue by lvqiushi** [apache/shardingsphere-elasticjob#1563]
the elastic job pom

            <dependency>
                <groupId>com.dangdang</groupId>
                <artifactId>elastic-job-lite-core</artifactId>
                <version>2.1.5</version>
                <exclusions>
                    <exclusion>
                        <artifactId>curator-client</artifactId>
                        <groupId>org.apache.curator</groupId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>com.dangdang</groupId>
                <artifactId>elastic-job-lite-spring</artifactId>
                <version>2.1.5</version>
            </dependency>

---------------------------------------------
when i use elastic job,i receive the error log.

Elastic job: create JobEventListener failure, error is: 
com.dangdang.ddframe.job.event.JobEventListenerConfigurationException: java.sql.SQLSyntaxErrorException: SELECT command denied to user 'xxxx' for table 'job_status_trace_log'
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbConfiguration.createJobEventListener(JobEventRdbConfiguration.java:48)
	at com.dangdang.ddframe.job.event.JobEventBus.register(JobEventBus.java:57)
	at com.dangdang.ddframe.job.event.JobEventBus.<init>(JobEventBus.java:52)
	at com.dangdang.ddframe.job.lite.api.JobScheduler.<init>(JobScheduler.java:79)
	at com.dangdang.ddframe.job.lite.spring.api.SpringJobScheduler.<init>(SpringJobScheduler.java:46)
	at com.qk.activity.config.job.JobConfig.slackActivitySchdule(JobConfig.java:71)
	at com.qk.activity.config.job.JobConfig$$EnhancerBySpringCGLIB$$7f7bce11.CGLIB$slackActivitySchdule$3(<generated>)
	at com.qk.activity.config.job.JobConfig$$EnhancerBySpringCGLIB$$7f7bce11$$FastClassBySpringCGLIB$$f58264bb.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
....
Caused by: java.sql.SQLSyntaxErrorException: SELECT command denied to user 'xxx' for table 'job_status_trace_log'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at com.mysql.cj.jdbc.DatabaseMetaData$6.forEach(DatabaseMetaData.java:2718)
	at com.mysql.cj.jdbc.DatabaseMetaData$6.forEach(DatabaseMetaData.java:2705)
	at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:56)
	at com.mysql.cj.jdbc.DatabaseMetaData.getIndexInfo(DatabaseMetaData.java:2775)
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.createTaskIdIndexIfNeeded(JobEventRdbStorage.java:93)
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.createJobStatusTraceTableAndIndexIfNeeded(JobEventRdbStorage.java:88)
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.initTablesAndIndexes(JobEventRdbStorage.java:67)
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.<init>(JobEventRdbStorage.java:61)
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbListener.<init>(JobEventRdbListener.java:37)
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbConfiguration.createJobEventListener(JobEventRdbConfiguration.java:46)

I have given relevant permissions in the database,How can I handle this situation？

**Comment by wwj-go** [comment]
Maybe you should execute 
` flush privileges`
for your mysql server?

**Comment by lvqiushi** [comment]
its work when I change the mysql auth with  `GRANT SELECT *.* TO 'admin'@'%'` 
I think the elastic job must require the ` SELECT *.* ` auth  instead of ` SELECT database.* `

**Comment by terrymanu** [comment]
Please set correct permission for the database
