### ISSUE TITLE
What is the reason to check job class confliction

### ISSUE THREAD

**Issue by kaihekaihe** [apache/shardingsphere-elasticjob#1595]
Exception occurs while restarting elasticjob APP after Job Class name is changed。I manually modify the class name stored in zk，and it works。

is there any other solutions？what is the reason to check job confliction ？ 

Caused by: org.apache.shardingsphere.elasticjob.infra.exception.JobConfigurationException: Job conflict with register center. The job 'simpleJob' in register center's class is 'com.oppo.paas.cloudjob.example.job.SpringBootSimpleJob1', your job class is 'com.oppo.paas.cloudjob.example.job.SpringBootSimpleJob'
	at org.apache.shardingsphere.elasticjob.lite.internal.config.ConfigurationService.checkConflictJob(ConfigurationService.java:86) ~[elasticjob-lite-core-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.shardingsphere.elasticjob.lite.internal.config.ConfigurationService.setUpJobConfiguration(ConfigurationService.java:70) ~[elasticjob-lite-core-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.shardingsphere.elasticjob.lite.internal.setup.SetUpFacade.setUpJobConfiguration(SetUpFacade.java:70) ~[elasticjob-lite-core-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobScheduler.<init>(JobScheduler.java:88) ~[elasticjob-lite-core-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.shardingsphere.elasticjob.lite.api.bootstrap.impl.ScheduleJobBootstrap.<init>(ScheduleJobBootstrap.java:43) ~[elasticjob-lite-core-3.0.0-alpha.jar:3.0.0-alpha]
	at org.apache.shardingsphere.elasticjob.lite.spring.boot.job.ElasticJobLiteAutoConfiguration.registerClassedJob(ElasticJobLiteAutoConfiguration.java:114) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.spring.boot.job.ElasticJobLiteAutoConfiguration.constructJobBootstraps(ElasticJobLiteAutoConfiguration.java:97) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.spring.boot.job.ElasticJobLiteAutoConfiguration.createJobBootstrapBeans(ElasticJobLiteAutoConfiguration.java:70) ~[classes/:na]

**Comment by gzdzss** [comment]
Did you set overwrite=true?

**Comment by TeslaCN** [comment]
> Did you set overwrite=true?

At present, job class cannot be overwritten.
