### ISSUE TITLE
Testcase TaskResultStatisticJobTest#assertExecute may fail

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere-elasticjob#1776]
## Bug Report

Ref: https://github.com/apache/shardingsphere-elasticjob/runs/1555591106

```
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE! - in org.apache.shardingsphere.elasticjob.cloud.scheduler.statistics.job.TaskResultStatisticJobTest
assertExecute(org.apache.shardingsphere.elasticjob.cloud.scheduler.statistics.job.TaskResultStatisticJobTest)  Time elapsed: 0.001 sec  <<< FAILURE!
org.mockito.exceptions.verification.TooManyActualInvocations: 

repository.add(
    <any org.apache.shardingsphere.elasticjob.cloud.statistics.type.task.TaskResultStatistics>
);
Wanted 9 times:
-> at org.apache.shardingsphere.elasticjob.cloud.statistics.rdb.StatisticRdbRepository.add(StatisticRdbRepository.java:164)
But was 10 times. Undesired invocation:
-> at org.apache.shardingsphere.elasticjob.cloud.scheduler.statistics.job.TaskResultStatisticJob.execute(TaskResultStatisticJob.java:90)

	at org.apache.shardingsphere.elasticjob.cloud.scheduler.statistics.job.TaskResultStatisticJobTest.assertExecute(TaskResultStatisticJobTest.java:106)

Running org.apache.shardingsphere.elasticjob.cloud.scheduler.statistics.StatisticManagerTest
Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.apache.shardingsphere.elasticjob.cloud.scheduler.statistics.StatisticManagerTest
Running org.apache.shardingsphere.elasticjob.cloud.scheduler.statistics.StatisticsSchedulerTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.apache.shardingsphere.elasticjob.cloud.scheduler.statistics.StatisticsSchedulerTest
Running org.apache.shardingsphere.elasticjob.cloud.scheduler.statistics.TaskResultMetaDataTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.apache.shardingsphere.elasticjob.cloud.scheduler.statistics.TaskResultMetaDataTest
Running org.apache.shardingsphere.elasticjob.cloud.scheduler.statistics.util.StatisticTimeUtilsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.apache.shardingsphere.elasticjob.cloud.scheduler.statistics.util.StatisticTimeUtilsTest
Running org.apache.shardingsphere.elasticjob.cloud.scheduler.util.IOUtilsTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.apache.shardingsphere.elasticjob.cloud.scheduler.util.IOUtilsTest

Results :

Failed tests: 
  TaskResultStatisticJobTest.assertExecute:106 
repository.add(
    <any org.apache.shardingsphere.elasticjob.cloud.statistics.type.task.TaskResultStatistics>
);
Wanted 9 times:
-> at org.apache.shardingsphere.elasticjob.cloud.statistics.rdb.StatisticRdbRepository.add(StatisticRdbRepository.java:164)
But was 10 times. Undesired invocation:
-> at org.apache.shardingsphere.elasticjob.cloud.scheduler.statistics.job.TaskResultStatisticJob.execute(TaskResultStatisticJob.java:90)


Tests run: 329, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by TeslaCN** [comment]
I run this testcase repeatly and I found memory leak occurred.

![image](https://user-images.githubusercontent.com/20503072/102290184-70260800-3f7b-11eb-8040-c4a8e05e9031.png)

![image](https://user-images.githubusercontent.com/20503072/102290125-4ec51c00-3f7b-11eb-86c9-f03ac8de6848.png)

**Comment by linghengqian** [comment]
- Follow https://lists.apache.org/thread/1k6zkvx9dwf2hq2xbb1ngxyxrhw5rd23 .  Affected by the Mesos upstream ecosystem, discussions have been opened to remove ElasticJob Cloud.

- This issue looks like it will no longer be relevant.

**Comment by linghengqian** [comment]
Since both ElasticJob Cloud and mesos integration modules have been removed from the master branch, close the current issue.
