### ISSUE TITLE
A start error with log “com.dangdang.ddframe.job.exception.JobSystemException: org.quartz.SchedulerException: The Scheduler has been shutdown.”

### ISSUE THREAD

**Issue by jgroups** [apache/shardingsphere-elasticjob#1790]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.dangdang.ddframe.job.lite.spring.api.SpringJobScheduler#0': Invocation of init method failed; nested exception is com.dangdang.ddframe.job.exception.JobSystemException: org.quartz.SchedulerException: The Scheduler has been shutdown.
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
 Caused by: 
com.dangdang.ddframe.job.exception.JobSystemException: org.quartz.SchedulerException: The Scheduler has been shutdown.
 at com.dangdang.ddframe.job.lite.internal.schedule.JobScheduleController.scheduleJob(JobScheduleController.java:57)
 at com.dangdang.ddframe.job.lite.api.JobScheduler.init(JobScheduler.java:111)

**Comment by TeslaCN** [comment]
Hi @jgroups 
We need to know how to reproduce this problem.

**Comment by linghengqian** [comment]
- I was unable to reproduce this issue on Spring Boot 3.3.2, see #2417.
