### ISSUE TITLE
org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x300c45dbff90003, likely server has closed socket

### ISSUE THREAD

**Issue by ChenJincheng-Gencent** [apache/shardingsphere-elasticjob#1830]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ElasticJob did you use?

3.0.0-RC1 and zk version is 3.6.2 and curator version is 5.1.0

### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?

ElasticJob-Lite

### Actual behavior
it throws exception continuously. The stack info is 
2021-02-08 19:37:28.266  INFO 1128 --- [           main] org.quartz.impl.StdSchedulerFactory      : Using default implementation for ThreadExecutor
2021-02-08 19:37:28.275  INFO 1128 --- [           main] org.quartz.core.SchedulerSignalerImpl    : Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2021-02-08 19:37:28.275  INFO 1128 --- [           main] org.quartz.core.QuartzScheduler          : Quartz Scheduler v.2.3.2 created.
2021-02-08 19:37:28.275  INFO 1128 --- [           main] o.a.s.e.l.i.s.JobShutdownHookPlugin      : Registering Quartz shutdown hook. MyJob
2021-02-08 19:37:28.276  INFO 1128 --- [           main] org.quartz.simpl.RAMJobStore             : RAMJobStore initialized.
2021-02-08 19:37:28.276  INFO 1128 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler meta-data: Quartz Scheduler (v2.3.2) 'MyJob' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2021-02-08 19:37:28.276  INFO 1128 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'MyJob' initialized from an externally provided properties instance.
2021-02-08 19:37:28.276  INFO 1128 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.3.2
2021-02-08 19:37:28.285  INFO 1128 --- [           main] org.apache.curator.utils.Compatibility   : Using org.apache.zookeeper.server.quorum.MultipleAddresses
2021-02-08 19:37:28.293  WARN 1128 --- [8.117.130:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x300c45dbff90003 for sever juncheng3/192.168.117.130:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.

org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x300c45dbff90003, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1275)

2021-02-08 19:37:28.395  INFO 1128 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : State change: SUSPENDED
2021-02-08 19:37:28.981  INFO 1128 --- [8.117.129:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server juncheng2/192.168.117.129:2181.
2021-02-08 19:37:28.981  INFO 1128 --- [8.117.129:2181)] org.apache.zookeeper.ClientCnxn          : SASL config status: Will not attempt to authenticate using SASL (unknown error)
2021-02-08 19:37:28.982  INFO 1128 --- [8.117.129:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established, initiating session, client: /192.168.117.1:57685, server: juncheng2/192.168.117.129:2181
2021-02-08 19:37:28.983  INFO 1128 --- [8.117.129:2181)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server juncheng2/192.168.117.129:2181, session id = 0x300c45dbff90003, negotiated timeout = 40000
2021-02-08 19:37:28.983  INFO 1128 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : State change: RECONNECTED
2021-02-08 19:37:29.397  WARN 1128 --- [8.117.129:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x300c45dbff90003 for sever juncheng2/192.168.117.129:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.

### Steps to reproduce the behavior.

mycode is 
new ScheduleJobBootstrap(regCenter, new JavaSimpleJob(), JobConfiguration.newBuilder("javaSimpleJob", 3)
                .cron("0/5 * * * * ?").shardingItemParameters("0=Beijing,1=Shanghai,2=Guangzhou").addExtraConfigurations(tracingConfig).build()).schedule();

### Example codes for reproduce this issue (such as a github link).
my project github link is https://github.com/ChenJincheng-Gencent/square-pavilion/blob/master/mall/mall-job-application/src/main/java/com/square/mall/job/application/handler/ScheduledTaskBeanProcessor.java

**Comment by TeslaCN** [comment]
Make sure your Zookeeper server's version >= 3.6.0

**Comment by ChenJincheng-Gencent** [comment]
> Make sure your Zookeeper server's version >= 3.6.0

You are right. I made a mistake. My Zookeeper server's version is not 3.6.2. I did not upgrade it with "bin" tar.gz. So it does not work. Thank you very much.
