### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.curator.connection.ConnectionHandlingPolicy

### ISSUE THREAD

**Issue by cielswift** [apache/shardingsphere-elasticjob#1831]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/curator/connection/ConnectionHandlingPolicy
	at org.apache.curator.framework.CuratorFrameworkFactory.builder(CuratorFrameworkFactory.java:78)
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.init(ZookeeperRegistryCenter.java:72)
	at com.ciel.fast.elastjob.ThJob.createRegistryCenter(ThJob.java:46)
	at com.ciel.fast.elastjob.ThJob.main(ThJob.java:34)
Caused by: java.lang.ClassNotFoundException: org.apache.curator.connection.ConnectionHandlingPolicy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 4 more

--------------------------------------------------------------------------------------------------------------------

after....................................

<dependency> 
            <groupId>org.apache.shardingsphere.elasticjob</groupId>
            <artifactId>elasticjob-lite-core</artifactId>
            <version>3.0.0-RC1</version>
        </dependency>

        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-recipes</artifactId>
            <version>2.10.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>2.10.0</version>
        </dependency>

Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
	at org.apache.curator.framework.listen.ListenerContainer.addListener(ListenerContainer.java:41)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.start(CuratorFrameworkImpl.java:257)
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.init(ZookeeperRegistryCenter.java:98)
	at com.ciel.fast.elastjob.ThJob.createRegistryCenter(ThJob.java:46)
	at com.ciel.fast.elastjob.ThJob.main(ThJob.java:34)

**Comment by TeslaCN** [comment]
Hi @cielswift 
The ElasticJob 3.0.0-RC1 requires Curator 5.1.0

**Comment by TeslaCN** [comment]
Close due to no response.
