### ISSUE TITLE
org.quartz.SchedulerException: TriggerListener 'JobTriggerListener' threw exception: java.lang.IllegalStateException: instance must be started before calling this method

### ISSUE THREAD

**Issue by www-haifeng** [apache/shardingsphere-elasticjob#2058]
2022-03-03 11:49:54,177 ERROR [PrepaymentJob_QuartzSchedulerThread] core.ErrorLogger (QuartzScheduler.java:2407) - Error notifying listeners of trigger misfire.
org.quartz.SchedulerException: TriggerListener 'JobTriggerListener' threw exception: java.lang.IllegalStateException: instance must be started before calling this method
	at org.quartz.core.QuartzScheduler.notifyTriggerListenersMisfired(QuartzScheduler.java:1889) [quartz-2.3.2.jar:?]
	at org.quartz.core.SchedulerSignalerImpl.notifyTriggerListenersMisfired(SchedulerSignalerImpl.java:74) [quartz-2.3.2.jar:?]
	at org.quartz.simpl.RAMJobStore.applyMisfire(RAMJobStore.java:1416) [quartz-2.3.2.jar:?]
	at org.quartz.simpl.RAMJobStore.acquireNextTriggers(RAMJobStore.java:1474) [quartz-2.3.2.jar:?]
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:287) [quartz-2.3.2.jar:?]
Caused by: com.dangdang.ddframe.job.reg.exception.RegException: java.lang.IllegalStateException: instance must be started before calling this method
	at com.dangdang.ddframe.job.reg.exception.RegExceptionHandler.handleException(RegExceptionHandler.java:52) ~[elastic-job-common-core-2.1.4.jar:?]
	at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:162) ~[elastic-job-common-core-2.1.4.jar:?]
	at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:143) ~[elastic-job-common-core-2.1.4.jar:?]
	at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:72) ~[elastic-job-lite-core-2.1.4.jar:?]
	at com.dangdang.ddframe.job.lite.internal.server.ServerService.isEnableServer(ServerService.java:99) ~[elastic-job-lite-core-2.1.4.jar:?]
	at com.dangdang.ddframe.job.lite.internal.server.ServerService.isAvailableServer(ServerService.java:80) ~[elastic-job-lite-core-2.1.4.jar:?]
	at com.dangdang.ddframe.job.lite.internal.sharding.ShardingService.getLocalShardingItems(ShardingService.java:176) ~[elastic-job-lite-core-2.1.4.jar:?]
	at com.dangdang.ddframe.job.lite.internal.schedule.JobTriggerListener.triggerMisfired(JobTriggerListener.java:46) ~[elastic-job-lite-core-2.1.4.jar:?]
	at org.quartz.core.QuartzScheduler.notifyTriggerListenersMisfired(QuartzScheduler.java:1887) ~[quartz-2.3.2.jar:?]
	... 4 more
Caused by: java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[curator-client-2.13.0.jar:?]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:375) ~[curator-framework-2.13.0.jar:?]
	at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:158) ~[elastic-job-common-core-2.1.4.jar:?]
	at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:143) ~[elastic-job-common-core-2.1.4.jar:?]
	at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:72) ~[elastic-job-lite-core-2.1.4.jar:?]
	at com.dangdang.ddframe.job.lite.internal.server.ServerService.isEnableServer(ServerService.java:99) ~[elastic-job-lite-core-2.1.4.jar:?]
	at com.dangdang.ddframe.job.lite.internal.server.ServerService.isAvailableServer(ServerService.java:80) ~[elastic-job-lite-core-2.1.4.jar:?]
	at com.dangdang.ddframe.job.lite.internal.sharding.ShardingService.getLocalShardingItems(ShardingService.java:176) ~[elastic-job-lite-core-2.1.4.jar:?]
	at com.dangdang.ddframe.job.lite.internal.schedule.JobTriggerListener.triggerMisfired(JobTriggerListener.java:46) ~[elastic-job-lite-core-2.1.4.jar:?]
	at org.quartz.core.QuartzScheduler.notifyTriggerListenersMisfired(QuartzScheduler.java:1887) ~[quartz-2.3.2.jar:?]
	... 4 more

**Comment by TeslaCN** [comment]
Hi @www-haifeng 
Could you try the ElasticJob 3.0.1? The 2.1.4 is no longer maintained.

**Comment by TeslaCN** [comment]
Close due to no response.
