### ISSUE TITLE
Duplicate entry 'd18bba97-fb89-496c-8ba3-599d6c72297f' for key 'PRIMARY'

### ISSUE THREAD

**Issue by init232** [apache/shardingsphere-elasticjob#2059]
日志.
时间:2022-03-08 14:49:35
event:
error
error.kind:
java.sql.SQLIntegrityConstraintViolationException
message:
Duplicate entry 'd18bba97-fb89-496c-8ba3-599d6c72297f' for key 'PRIMARY'
stack:
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'd18bba97-fb89-496c-8ba3-599d6c72297f' for key 'PRIMARY'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
at com.mysql.cj.jdbc.ClientPreparedStatement.execute$original$YOtsXTmA(ClientPreparedStatement.java:370)
at com.mysql.cj.jdbc.ClientPreparedStatement.execute$original$YOtsXTmA$accessor$TCnxFK8Y(ClientPreparedStatement.java)
at com.mysql.cj.jdbc.ClientPreparedStatement$auxiliary$2HqQadC3.call(Unknown Source)
at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java)
at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
at org.apache.shardingsphere.elasticjob.tracing.rdb.storage.RDBJobEventStorage.insertJobExecutionEventWhenSuccess(RDBJobEventStorage.java:233)
at org.apache.shardingsphere.elasticjob.tracing.rdb.storage.RDBJobEventStorage.updateJobExecutionEventWhenSuccess(RDBJobEventStorage.java:208)
at org.apache.shardingsphere.elasticjob.tracing.rdb.storage.RDBJobEventStorage.addJobExecutionEvent(RDBJobEventStorage.java:167)
at org.apache.shardingsphere.elasticjob.tracing.rdb.listener.RDBTracingListener.listen(RDBTracingListener.java:41)
at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by linghengqian** [comment]
- Can you provide an example git with unit tests in elasticjob 3.0.3?

**Comment by lzp16** [comment]
如果作业执行逻辑过于简单，比如只是打印一个日志，并且同一个分片的JobExecutionEvent插入和更新是通过EventBus异步操作的，那么就会出现数据库正在执行插入时，又进行了更新操作，默认情况下，数据库是读已提交，通过id更新失败转而进行插入操作，因而就会出现id重复的问题。

**Comment by linghengqian** [comment]
> 如果作业执行逻辑过于简单，比如只是打印一个日志，并且同一个分片的JobExecutionEvent插入和更新是通过EventBus异步操作的，那么就会出现数据库正在执行插入时，又进行了更新操作，默认情况下，数据库是读已提交，通过id更新失败转而进行插入操作，因而就会出现id重复的问题。

- Would you like to submit a PR with a fix that includes unit tests?

**Comment by linghengqian** [comment]
Cannot reproduce in master branch. Please provide unit tests.

**Comment by linghengqian** [comment]
Closed due to complete inability to reproduce in master branch.
