### ISSUE TITLE
增加实例后立即分配尚未执行的分片

### ISSUE THREAD

**Issue by jingting-zhang** [apache/shardingsphere-elasticjob#2060]
elastic-job不支持新增实例后立即再分片（把已分配但未执行的分片重新分配给新增的实例），只能等下次执行周期再重新分片。这个能否支持，有无必要支持？

**Comment by TeslaCN** [comment]
Hi @jingting-zhang 
Please translate your issue into English.
Could you tell us something about your scenario? Is there any problem that doing reshard before next execution?

**Comment by takeseem** [comment]
如果没有分片信息，UI界面上很多操作都无法执行，如触发。详情也无法点击进入，否则NPE:https://github.com/apache/shardingsphere-elasticjob-ui/issues/154

原因是：https://github.com/apache/shardingsphere-elasticjob/blob/master/elasticjob-lite/elasticjob-lite-lifecycle/src/main/java/org/apache/shardingsphere/elasticjob/lite/lifecycle/internal/statistics/ShardingStatisticsAPIImpl.java#L64

`JobInstance jobInstance = YamlEngine.unmarshal(regCenter.get(jobNodePath.getInstanceNodePath(instanceId)), JobInstance.class);`
regCenter.get将返回null

```
[ERROR] 01:33:13.385 [http-nio-8118-exec-9] o.a.s.e.l.u.w.h.RestExceptionHandler - null
java.lang.NullPointerException: null
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:64)
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:47)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:427)
	at org.apache.shardingsphere.elasticjob.infra.yaml.YamlEngine.unmarshal(YamlEngine.java:50)
	at org.apache.shardingsphere.elasticjob.lite.lifecycle.internal.statistics.ShardingStatisticsAPIImpl.getShardingInfo(ShardingStatisticsAPIImpl.java:64)
	at org.apache.shardingsphere.elasticjob.lite.lifecycle.internal.statistics.ShardingStatisticsAPIImpl.getShardingInfo(ShardingStatisticsAPIImpl.java:47)
	at org.apache.shardingsphere.elasticjob.lite.ui.web.controller.JobOperationController.getShardingInfo(JobOperationController.java:125)
```
