### ISSUE TITLE
elasticjob-lite will Close the zk connection after task down

### ISSUE THREAD

**Issue by x92811x** [apache/shardingsphere-elasticjob#2137]
## Question

1. Which version of ElasticJob did you use?

3.0.0

2. Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?

ElasticJob-Lite

3. Phenomenon of the problem

[TraceId:] 2022-10-14 11:12:55,173 [WARN] [main-SendThread(172.18.42.107:2181)] [org.apache.zookeeper.ClientCnxn$SendThread] - An exception was thrown while closing send thread for session 0x20882478db10031.
org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x20882478db10031, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:75) ~[zookeeper-3.6.0.jar:3.6.0]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:348) ~[zookeeper-3.6.0.jar:3.6.0]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1262) [zookeeper-3.6.0.jar:3.6.0]
[TraceId:] 2022-10-14 11:12:55,289 [INFO] [main-EventThread] [org.apache.zookeeper.ClientCnxn$EventThread] - EventThread shut down for session: 0x20882478db10031
[TraceId:] 2022-10-14 11:12:55,290 [INFO] [http-nio2-8060-exec-7] [org.apache.zookeeper.ZooKeeper] - Session: 0x20882478db10031 closed
[TraceId:] 2022-10-14 11:13:00,002 [ERROR] [JiaoYiCenterClientQyscTimer_Worker-1] [org.quartz.core.JobRunShell] - Job DEFAULT.JiaoYiCenterClientQyscTimer threw an unhandled Exception: 
org.apache.shardingsphere.elasticjob.reg.exception.RegException: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.shardingsphere.elasticjob.reg.exception.RegExceptionHandler.handleException(RegExceptionHandler.java:48) ~[elasticjob-registry-center-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:162) ~[elasticjob-registry-center-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:143) ~[elasticjob-registry-center-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:77) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.config.ConfigurationService.load(ConfigurationService.java:52) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJobFacade.loadJobConfiguration(LiteJobFacade.java:76) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:77) ~[elasticjob-executor-kernel-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.execute(LiteJob.java:35) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar:?]
Caused by: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:823) ~[curator-client-5.1.0.jar:?]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:423) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:457) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:158) ~[elasticjob-registry-center-3.0.0.jar:3.0.0]
	... 8 more
[TraceId:] 2022-10-14 11:13:00,065 [ERROR] [JiaoYiCenterClientQyscTimer_Worker-1] [org.quartz.core.ErrorLogger] - Job (DEFAULT.JiaoYiCenterClientQyscTimer threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-2.3.2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar:?]
Caused by: org.apache.shardingsphere.elasticjob.reg.exception.RegException: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.shardingsphere.elasticjob.reg.exception.RegExceptionHandler.handleException(RegExceptionHandler.java:48) ~[elasticjob-registry-center-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:162) ~[elasticjob-registry-center-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:143) ~[elasticjob-registry-center-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:77) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.config.ConfigurationService.load(ConfigurationService.java:52) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJobFacade.loadJobConfiguration(LiteJobFacade.java:76) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:77) ~[elasticjob-executor-kernel-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.execute(LiteJob.java:35) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar:?]
	... 1 more
Caused by: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:823) ~[curator-client-5.1.0.jar:?]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:423) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:457) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:158) ~[elasticjob-registry-center-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:143) ~[elasticjob-registry-center-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:77) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.config.ConfigurationService.load(ConfigurationService.java:52) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJobFacade.loadJobConfiguration(LiteJobFacade.java:76) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:77) ~[elasticjob-executor-kernel-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.execute(LiteJob.java:35) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar:?]
	... 1 more

**Comment by TeslaCN** [comment]
Hi @x92811x 
Could you check whether the network is stable between application and ZooKeeper? What's your ZooKeeper's version?

**Comment by x92811x** [comment]
> Hi @x92811x Could you check whether the network is stable between application and ZooKeeper? What's your ZooKeeper's version?

yep,it's stable, zk version 3.6.2
application and ZooKeeper In the test environment is the same server，ZooKeeper  is Single-node deployment

**Comment by x92811x** [comment]
> Hi @x92811x Could you check whether the network is stable between application and ZooKeeper? What's your ZooKeeper's version?

the error log is other environment , because the test environment log is deleted
but the exception is the same

**Comment by TeslaCN** [comment]
Could you help us to reproduce this issue? I've checked the code and found no production code invoke close.
![image](https://user-images.githubusercontent.com/20503072/197724647-edfa318b-fbbc-4dce-891f-104155db2c66.png)

**Comment by x92811x** [comment]
> Could you help us to reproduce this issue? I've checked the code and found no production code invoke close.

when sometime free,I'll try again

**Comment by x92811x** [comment]
> Could you help us to reproduce this issue? I've checked the code and found no production code invoke close. ![image](https://user-images.githubusercontent.com/20503072/197724647-edfa318b-fbbc-4dce-891f-104155db2c66.png)

1.The timer has no task,throwing exception as well
2. zk status is effective，client error is reported

[root@hzhlht bin]# ./zkServer.sh status
ZooKeeper JMX enabled by default
Using config: /home/apache-zookeeper-3.6.2-bin/bin/../conf/zoo.cfg
Client port found: 2181. Client address: localhost. Client SSL: false.
Mode: standalone

[TraceId:] 2022-11-28 13:47:00,020 [ERROR] [JiaoYiCenterClientQyscTimer_Worker-1] [org.quartz.core.ErrorLogger] - Job (DEFAULT.JiaoYiCenterClientQyscTimer threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) [quartz-2.3.2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar:?]
Caused by: org.apache.shardingsphere.elasticjob.reg.exception.RegException: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.shardingsphere.elasticjob.reg.exception.RegExceptionHandler.handleException(RegExceptionHandler.java:48) ~[elasticjob-registry-center-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:162) ~[elasticjob-registry-center-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:143) ~[elasticjob-registry-center-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:77) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.config.ConfigurationService.load(ConfigurationService.java:52) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJobFacade.loadJobConfiguration(LiteJobFacade.java:76) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:77) ~[elasticjob-executor-kernel-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.execute(LiteJob.java:35) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar:?]
	... 1 more
Caused by: java.lang.IllegalStateException: Expected state [STARTED] was [STOPPED]
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:823) ~[curator-client-5.1.0.jar:?]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.checkState(CuratorFrameworkImpl.java:423) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:457) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:158) ~[elasticjob-registry-center-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:143) ~[elasticjob-registry-center-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:77) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.config.ConfigurationService.load(ConfigurationService.java:52) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJobFacade.loadJobConfiguration(LiteJobFacade.java:76) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.executor.ElasticJobExecutor.execute(ElasticJobExecutor.java:77) ~[elasticjob-executor-kernel-3.0.0.jar:3.0.0]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.execute(LiteJob.java:35) ~[elasticjob-lite-core-3.0.0.jar:3.0.0]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar:?]
	... 1 more

**Comment by TeslaCN** [comment]
We can hardly investigate this unless there is a minimal runnable project to help us reproduce.

**Comment by linghengqian** [comment]
Closed because it could not be reproduced.
