### ISSUE TITLE
When I register a transient task, the result returned is "Name cannot be null." 

### ISSUE THREAD

**Issue by huangyi81** [apache/shardingsphere-elasticjob#2159]
## When I register a transient task, the result returned is "Name cannot be null." 

![image](https://user-images.githubusercontent.com/119296492/205543145-5eff455b-6f70-4809-a627-4e3ec0bb37b2.png)

elasticjob-cloud version :3.0.2
mesos version: 1.11.0
zookeeper version: 3.7.1

How to solve this problem

**Comment by huangyi81** [comment]
[org.apache.curator.framework.listen.MappingListenerManager] Listener (org.apache.shardingsphere.elasticjob.cloud.scheduler.config.job.CloudJobConfigurationListener@3d263a0f) threw an exception 
java.lang.IllegalArgumentException: Name cannot be null.
	at org.quartz.utils.Key.<init>(Key.java:62)
	at org.quartz.JobKey.<init>(JobKey.java:66)
	at org.quartz.JobKey.jobKey(JobKey.java:70)
	at org.apache.shardingsphere.elasticjob.cloud.scheduler.producer.TransientProducerScheduler.buildJobKey(TransientProducerScheduler.java:125)
	at org.apache.shardingsphere.elasticjob.cloud.scheduler.producer.TransientProducerScheduler.register(TransientProducerScheduler.java:90)
	at org.apache.shardingsphere.elasticjob.cloud.scheduler.producer.ProducerManager.schedule(ProducerManager.java:145)
	at org.apache.shardingsphere.elasticjob.cloud.scheduler.config.job.CloudJobConfigurationListener.event(CloudJobConfigurationListener.java:59)
	at org.apache.curator.framework.recipes.cache.CuratorCacheImpl.lambda$putStorage$7(CuratorCacheImpl.java:279)
	at org.apache.curator.framework.listen.MappingListenerManager.lambda$forEach$0(MappingListenerManager.java:92)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by TeslaCN** [comment]
The `cron` is required.

**Comment by huangyi81** [comment]
I see that `cron` is not necessary in the manual, and the executor source code also handles the situation that `cron `is `null `or `empty`.

![image](https://user-images.githubusercontent.com/119296492/207019543-a3047978-e7e2-4ecf-915b-c268768e1c6b.png)
![image](https://user-images.githubusercontent.com/119296492/207205939-3a0d4660-b5ef-4c79-8f4f-6782ffd13fb4.png)

**Comment by linghengqian** [comment]
- Please follow https://lists.apache.org/thread/1k6zkvx9dwf2hq2xbb1ngxyxrhw5rd23 .  Affected by the Mesos upstream ecosystem, discussions have been opened to remove ElasticJob Cloud.

**Comment by linghengqian** [comment]
Since both ElasticJob Cloud and mesos integration modules have been removed from the master branch, close the current issue.
