### ISSUE TITLE
Why keep such errors, although the task can be executed normally

### ISSUE THREAD

**Issue by zyz199221** [apache/shardingsphere-elasticjob#2223]
![image](https://github.com/apache/shardingsphere-elasticjob/assets/17791958/1b06a97a-a00e-4a72-8ee3-39ffbb6644c8)

ERROR o.apache.curator.framework.recipes.cache.TreeCache - 
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1479)
        at java.util.HashMap$EntryIterator.next(HashMap.java:1477)
        at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.findTreeCache(ZookeeperRegistryCenter.java:147)
        at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:135)
        at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:72)
        at com.dangdang.ddframe.job.lite.internal.election.LeaderService.isLeader(LeaderService.java:84)
        at com.dangdang.ddframe.job.lite.internal.election.ElectionListenerManager$LeaderAbdicationJobListener.dataChanged(ElectionListenerManager.java:91)
        at com.dangdang.ddframe.job.lite.internal.listener.AbstractJobListener.childEvent(AbstractJobListener.java:44)
        at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:732)
        at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:726)
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:296)
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85)
        at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:725)
        at org.apache.curator.framework.recipes.cache.TreeCache.access$1400(TreeCache.java:71)
        at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:843)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by linghengqian** [comment]
- Can you provide an example git with unit tests?

**Comment by linghengqian** [comment]
Closed due to lack of reproducible unit tests and no response.
