### ISSUE TITLE
org.apache.zookeeper.KeeperException$NoNodeException

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere-elasticjob#2392]
```
2024-05-24T02:58:48.097860668Z [INFO ] 2024-05-24 10:58:48.097 [ShardingSphere-Curator-listener-metadata] org.quartz.core.QuartzScheduler - Scheduler new.949f2203_$_NON_CLUSTERED shutdown complete.
2024-05-24T02:58:48.104947976Z [ERROR] 2024-05-24 10:58:48.104 [Curator-Framework-0] o.a.c.f.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up
2024-05-24T02:58:48.104959193Z org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /ss2/_new.949f2203/leader/election
2024-05-24T02:58:48.104961549Z  at org.apache.zookeeper.KeeperException.create(KeeperException.java:118)
2024-05-24T02:58:48.104963573Z  at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
2024-05-24T02:58:48.104965655Z  at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1347)
2024-05-24T02:58:48.104967651Z  at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:351)
2024-05-24T02:58:48.104969563Z  at org.apache.curator.framework.imps.CreateBuilderImpl$8.performBackgroundOperation(CreateBuilderImpl.java:775)
2024-05-24T02:58:48.104971545Z  at org.apache.curator.framework.imps.OperationAndData.callPerformBackgroundOperation(OperationAndData.java:84)
2024-05-24T02:58:48.104973481Z  at org.apache.curator.framework.imps.CuratorFrameworkImpl.performBackgroundOperation(CuratorFrameworkImpl.java:1008)
2024-05-24T02:58:48.104975539Z  at org.apache.curator.framework.imps.CuratorFrameworkImpl.backgroundOperationsLoop(CuratorFrameworkImpl.java:986)
2024-05-24T02:58:48.104977433Z  at org.apache.curator.framework.imps.CuratorFrameworkImpl.access$300(CuratorFrameworkImpl.java:97)
2024-05-24T02:58:48.104979350Z  at org.apache.curator.framework.imps.CuratorFrameworkImpl$4.call(CuratorFrameworkImpl.java:376)
2024-05-24T02:58:48.104985289Z  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-05-24T02:58:48.104987571Z  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
2024-05-24T02:58:48.104989550Z  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-05-24T02:58:48.104991532Z  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-05-24T02:58:48.104993415Z  at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by songxiaosheng** [comment]
看着像关闭进程引起的，后面增加空指针判断

**Comment by linghengqian** [comment]
I was actually unable to reproduce this bug using the master branch.
