### ISSUE TITLE
`BaseSnapshotServiceE2ETest` should not occupy port 9000 of the host

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere-elasticjob#2408]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
- For #2407 .
### Describe the feature you would like.
- `BaseSnapshotServiceE2ETest` should not occupy port 9000 of the host. This manifests itself in a conflict with `portainer/portainer-ee`. Feel free to do the following.
```shell
docker volume create portainer_data
docker run -d -p 8000:8000 -p 9443:9443 -p 9000:9000 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ee:latest

sdk install java 21.0.2-graalce
sdk use java 21.0.2-graalce
git clone git@github.com:apache/shardingsphere-elasticjob.git
cd ./shardingsphere-elasticjob/
./mvnw '-Dmaven.javadoc.skip=true' clean install -T1C
```
- This results in the following failure.
```shell
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.395 s <<< FAILURE! -- in org.apache.shardingsphere.elasticjob.test.e2e.snapshot.SnapshotServiceEnableE2ETest
[ERROR] org.apache.shardingsphere.elasticjob.test.e2e.snapshot.SnapshotServiceEnableE2ETest.assertMonitorWithCommand -- Time elapsed: 0.054 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 
expected: <HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad Request
> but was: <>
        at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
        at org.apache.shardingsphere.elasticjob.test.e2e.snapshot.SnapshotServiceEnableE2ETest.assertMonitorWithCommand(SnapshotServiceEnableE2ETest.java:50)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   SnapshotServiceEnableE2ETest.assertMonitorWithCommand:50 expected: <HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close

400 Bad Request
> but was: <>
[INFO] 
[ERROR] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0

```

**Comment by linghengqian** [comment]
- I am working on the current issue.
