### ISSUE TITLE
How to extend AbstractDistributeOnceElasticJobListener and config by using  SPI

### ISSUE THREAD

**Issue by weiro-9-w7** [apache/shardingsphere-elasticjob#2430]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

1.  create class and extend AbstractDistributeOnceElasticJobListener
     @Slf4j
      public class DistributeOnceJobJobListener extends AbstractDistributeOnceElasticJobListener implements ElasticJobListener {
      
        public DistributeOnceJobJobListener(long startedTimeoutMilliseconds, long completedTimeoutMilliseconds) {
          super(startedTimeoutMilliseconds, completedTimeoutMilliseconds);
        }
      
        @Override
        public void doBeforeJobExecutedAtLastStarted(ShardingContexts shardingContexts) {
          log.info(shardingContexts.getJobName() + " begin distribute job executed");
        }
      
        @Override
        public void doAfterJobExecutedAtLastCompleted(ShardingContexts shardingContexts) {
          log.info(shardingContexts.getJobName() + " end distribute job executed");
        }
      
        @Override
        public String getType() {
          return "distributeOnceJobListener";
        }
      }
3.  config the org.apache.shardingsphere.elasticjob.infra.listener.ElasticJobListener and specify the class
     org.example.elatisjobtest.job.DistributeOnceJobJobListener
5.  start the app and throw exception, ServiceLoader can't find the Constructor

     Caused by: java.lang.NoSuchMethodException: org.example.elatisjobtest.job.DistributeOnceJobJobListener.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585) ~[na:na]
	at java.base/java.lang.Class.getConstructor(Class.java:2271) ~[na:na]
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:666) ~[na:na]
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:663) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569) ~[na:na]
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674) ~[na:na]
	... 44 common frames omitted

**Comment by weiro-9-w7** [comment]
elastic - job version is 3.0.4
