### ISSUE TITLE
Job conflict with register center when  class has been enhanced multiple times

### ISSUE THREAD

**Issue by aaron19940513** [apache/shardingsphere-elasticjob#2451]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ElasticJob did you use?
elasticjob 3.0.1
druid 1.1.21

### Actual behavior
org.apache.shardingsphere.elasticjob.infra.exception.JobConfigurationException: Job conflict with register center. The job 'FileScanDateInitJob' in register center's class is 'com.***.business.handler.filemanage.FileScanDateInitJob', your job class is 'com.eastmoney.amp.settlement.business.handler.filemanage.FileScanDateInitJob$$EnhancerBySpringCGLIB$$da78c225'
	at org.apache.shardingsphere.elasticjob.lite.internal.config.ConfigurationService.checkConflictJob(ConfigurationService.java:86)
	at org.apache.shardingsphere.elasticjob.lite.internal.config.ConfigurationService.setUpJobConfiguration(ConfigurationService.java:70)
	at org.apache.shardingsphere.elasticjob.lite.internal.setup.SetUpFacade.setUpJobConfiguration(SetUpFacade.java:66)
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.JobScheduler.<init>(JobScheduler.java:84)
	at org.apache.shardingsphere.elasticjob.lite.api.bootstrap.impl.ScheduleJobBootstrap.<init>(ScheduleJobBootstrap.java:36)
	at org.apache.shardingsphere.elasticjob.lite.spring.boot.job.ElasticJobBootstrapConfiguration.registerClassedJob(ElasticJobBootstrapConfiguration.java:108)
	at org.apache.shardingsphere.elasticjob.lite.spring.boot.job.ElasticJobBootstrapConfiguration.constructJobBootstraps(ElasticJobBootstrapConfiguration.java:91)
	at org.apache.shardingsphere.elasticjob.lite.spring.boot.job.ElasticJobBootstrapConfiguration.createJobBootstrapBeans(ElasticJobBootstrapConfiguration.java:64)
	at org.apache.shardingsphere.elasticjob.lite.spring.boot.job.ElasticJobBootstrapConfiguration.afterSingletonsInstantiated(ElasticJobBootstrapConfiguration.java:52)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:963)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:763)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339)
### Reason analyze (If you can)
This class has been enhanced multiple times
### Steps to reproduce the behavior.
I what to use druid admin to monitor some code, add the configuration below
spring.datasource.druid.aop-patterns = com.***.business.handler.*

**Comment by aaron19940513** [comment]
![image](https://github.com/user-attachments/assets/238440bc-e9b3-45d4-b377-d7b80628422d)

 need to backtrack twice to get the original class

**Comment by linghengqian** [comment]
- I highly doubt this is actually a bug in druid spring boot starter unless you can provide a PR with unit tests. See https://github.com/alibaba/druid/pull/6132 . 


- You can enable spring monitoring even without using druid spring boot starter. Consider the content in https://www.yuque.com/linghengqian/meve2v/zoy35sivtf6nzp90 . 

- I would not recommend using Alibaba druid before https://github.com/alibaba/druid/pull/6143 is reviewed. Alibaba druid has broken the integration of spring boot, hibernate, and flyway since 7 years ago.

**Comment by aaron19940513** [comment]
> * I highly doubt this is actually a bug in druid spring boot starter unless you can provide a PR with unit tests. See [Configuring `DefaultAdvisorAutoProxyCreator` when proxying via cglib alibaba/druid#6132](https://github.com/alibaba/druid/pull/6132) .
> * You can enable spring monitoring even without using druid spring boot starter. Consider the content in https://www.yuque.com/linghengqian/meve2v/zoy35sivtf6nzp90 .
> * I would not recommend using Alibaba druid before [Add property `closeConnOnFatalError` to match HikariCP's behavior alibaba/druid#6143](https://github.com/alibaba/druid/pull/6143) is reviewed. Alibaba druid has broken the integration of spring boot, hibernate, and flyway since 7 years ago.

I think you are right, this issue is caused by druid. After upgrading to the  latest version of Druid, there are no more issues

And Thanks  for your reminder, I will use druid carefully

**Comment by linghengqian** [comment]
- It looks like there is nothing to open a PR on the elasticjob side. I will close the current issue.
