### ISSUE TITLE
got ConcurrentModificationException when startup jobs

### ISSUE THREAD

**Issue by ymiao** [apache/shardingsphere-elasticjob#451]
Please answer these questions before submitting your issue. Thanks!

### Which version of Elastic-Job do you using?
2.1.0 lite

### Expected behavior
start jobs without exception

### Actual behavior
got exception
### Steps to reproduce the behavior
normal start, but cannot reproduce it every time

### Please provide the reproduce example codes (such as github link) if possible.

```
[ERROR] [dschedule] 2017-12-13 13:12:24: 6994 [Curator-TreeCache-1] ( TreeCache.java,751 ) - 
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
    at java.util.HashMap$EntryIterator.next(HashMap.java:962)
    at java.util.HashMap$EntryIterator.next(HashMap.java:960)
    at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.findTreeCache(ZookeeperRegistryCenter.java:147)
    at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:135)
    at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:72)
    at com.dangdang.ddframe.job.lite.internal.config.ConfigurationService.load(ConfigurationService.java:54)
    at com.dangdang.ddframe.job.lite.internal.failover.FailoverListenerManager.isJobCrashAndNeedFailover(FailoverListenerManager.java:82)
    at com.dangdang.ddframe.job.lite.internal.failover.FailoverListenerManager.failover(FailoverListenerManager.java:72)
    at com.dangdang.ddframe.job.lite.internal.failover.FailoverListenerManager.access$100(FailoverListenerManager.java:37)
    at com.dangdang.ddframe.job.lite.internal.failover.FailoverListenerManager$FailoverJobCrashedJobListener.dataChanged(FailoverListenerManager.java:99)
    at com.dangdang.ddframe.job.lite.internal.listener.AbstractJobListener.childEvent(AbstractJobListener.java:44)
```

**Comment by compilerduck** [comment]
This is caused by non thread-safe variable 'ZookeeperRegistryCenter.caches', has been fixed today. Please see issue #694
