### ISSUE TITLE
2.0.5 版本Tree-Cache blocked，任务卡住。已经出现好几次

### ISSUE THREAD

**Issue by Ah39** [apache/shardingsphere-elasticjob#515]
"GroupLevelCalculationJob_QuartzSchedulerThread" #124 prio=5 os_prio=0 tid=0x00007fc0195fe000 nid=0x68c7 in Object.wait() [0x00007fbef73f2000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1406)
	- locked <0x00000000a39bc740> (a org.apache.zookeeper.ClientCnxn$Packet)
	at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1097)
	at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:237)
	at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:226)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForegroundStandard(ExistsBuilderImpl.java:223)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForeground(ExistsBuilderImpl.java:216)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:175)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:32)
	at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.isExisted(ZookeeperRegistryCenter.java:210)
	at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.isJobNodeExisted(JobNodeStorage.java:66)
	at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.createJobNodeIfNeeded(JobNodeStorage.java:107)
	at com.dangdang.ddframe.job.lite.internal.execution.ExecutionService.setMisfire(ExecutionService.java:189)
	at com.dangdang.ddframe.job.lite.internal.schedule.JobTriggerListener.triggerMisfired(JobTriggerListener.java:47)
	at org.quartz.core.QuartzScheduler.notifyTriggerListenersMisfired(QuartzScheduler.java:1905)
	at org.quartz.core.SchedulerSignalerImpl.notifyTriggerListenersMisfired(SchedulerSignalerImpl.java:74)
	at org.quartz.simpl.RAMJobStore.applyMisfire(RAMJobStore.java:1354)
	at org.quartz.simpl.RAMJobStore.acquireNextTriggers(RAMJobStore.java:1412)
	- locked <0x00000000c0da2288> (a java.lang.Object)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:272)

   Locked ownable synchronizers:
	- None

"Curator-TreeCache-4" #120 daemon prio=5 os_prio=0 tid=0x00007fbf44014000 nid=0x68c3 waiting for monitor entry [0x00007fbef76f5000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.quartz.simpl.RAMJobStore.retrieveTrigger(RAMJobStore.java:585)
	- waiting to lock <0x00000000c0da2288> (a java.lang.Object)
	at org.quartz.core.QuartzScheduler.getTrigger(QuartzScheduler.java:1530)
	at org.quartz.impl.StdScheduler.getTrigger(StdScheduler.java:508)
	at com.dangdang.ddframe.job.lite.internal.schedule.JobScheduleController.rescheduleJob(JobScheduleController.java:73)
	at com.dangdang.ddframe.job.lite.internal.config.ConfigurationListenerManager$CronSettingAndJobEventChangedJobListener.dataChanged(ConfigurationListenerManager.java:63)
	at com.dangdang.ddframe.job.lite.internal.listener.AbstractJobListener.childEvent(AbstractJobListener.java:37)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:741)
	at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:735)
	at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)
	at org.apache.curator.shaded.com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
	at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85)
	at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:734)
	at org.apache.curator.framework.recipes.cache.TreeCache.access$1700(TreeCache.java:71)
	at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:852)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000000c0313630> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by terrymanu** [comment]
What is your zookeeper and curator version?

**Comment by terrymanu** [comment]
Fixed by #1060
