### ISSUE TITLE
项目集成spring boot报错，什么原因呢

### ISSUE THREAD

**Issue by qwzhang01** [apache/shardingsphere-elasticjob#564]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
08-14 12:21:04.004 ERROR [org.springframework.boot.SpringApplication] - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'simpleJobScheduler' defined in class path resource [com/bloom/oms/conf/job/StockJobConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.dangdang.ddframe.job.lite.api.JobScheduler]: Factory method 'simpleJobScheduler' threw exception; nested exception is java.lang.IllegalAccessError: tried to access method com.dangdang.ddframe.job.event.JobEventBus.<init>()V from class com.dangdang.ddframe.job.lite.api.JobScheduler
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:624)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1282)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1126)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:829)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:865)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:548)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1252)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1240)
	at com.bloom.oms.BloomOmsApplication.main(BloomOmsApplication.java:20)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.dangdang.ddframe.job.lite.api.JobScheduler]: Factory method 'simpleJobScheduler' threw exception; nested exception is java.lang.IllegalAccessError: tried to access method com.dangdang.ddframe.job.event.JobEventBus.<init>()V from class com.dangdang.ddframe.job.lite.api.JobScheduler
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:619)
	... 19 common frames omitted
Caused by: java.lang.IllegalAccessError: tried to access method com.dangdang.ddframe.job.event.JobEventBus.<init>()V from class com.dangdang.ddframe.job.lite.api.JobScheduler
	at com.dangdang.ddframe.job.lite.api.JobScheduler.<init>(JobScheduler.java:74)
	at com.dangdang.ddframe.job.lite.spring.api.SpringJobScheduler.<init>(SpringJobScheduler.java:40)
	at com.bloom.oms.conf.job.StockJobConfig.simpleJobScheduler(StockJobConfig.java:29)
	at com.bloom.oms.conf.job.StockJobConfig$$EnhancerBySpringCGLIB$$7a43477f.CGLIB$simpleJobScheduler$0(<generated>)
	at com.bloom.oms.conf.job.StockJobConfig$$EnhancerBySpringCGLIB$$7a43477f$$FastClassBySpringCGLIB$$fd1188c1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.bloom.oms.conf.job.StockJobConfig$$EnhancerBySpringCGLIB$$7a43477f.simpleJobScheduler(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 20 common frames omitted

**Comment by microlmj** [comment]
我的也是这个问题 A component required a bean of type 'com.dangdang.ddframe.job.event.JobEventConfiguration' that could not be found.

**Comment by terrymanu** [comment]
Will support spring boot starter at #970
