### ISSUE TITLE
oracle 11g 创建事件监听时报错

### ISSUE THREAD

**Issue by Portg** [apache/shardingsphere-elasticjob#576]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）

正常创建时间跟踪表

### Actual behavior （实际运行的结果是）
Caused by: oracle.jdbc.OracleDatabaseException: ORA-00911: 无效字符

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498) ~[ojdbc8.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446) ~[ojdbc8.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054) ~[ojdbc8.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623) ~[ojdbc8.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252) ~[ojdbc8.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612) ~[ojdbc8.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:226) ~[ojdbc8.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:59) ~[ojdbc8.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:910) ~[ojdbc8.jar:12.2.0.1.0]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119) ~[ojdbc8.jar:12.2.0.1.0]
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780) ~[ojdbc8.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1343) ~[ojdbc8.jar:12.2.0.1.0]
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3887) ~[ojdbc8.jar:12.2.0.1.0]
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1079) ~[ojdbc8.jar:12.2.0.1.0]
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.createJobStatusTraceTable(JobEventRdbStorage.java:140) ~[elastic-job-common-core-2.1.5.jar:?]
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.createJobStatusTraceTableAndIndexIfNeeded(JobEventRdbStorage.java:85) ~[elastic-job-common-core-2.1.5.jar:?]
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.initTablesAndIndexes(JobEventRdbStorage.java:67) ~[elastic-job-common-core-2.1.5.jar:?]
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.<init>(JobEventRdbStorage.java:61) ~[elastic-job-common-core-2.1.5.jar:?]
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbListener.<init>(JobEventRdbListener.java:37) ~[elastic-job-common-core-2.1.5.jar:?]
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbConfiguration.createJobEventListener(JobEventRdbConfiguration.java:46) ~[elastic-job-common-core-2.1.5.jar:?]
	... 72 more
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by KerwinAusten** [comment]
他们的建表语句的字段两边加了``符号，在Oracle下边就会报错，但是MySql不会，可以通过修改源码解决。位置是JobEventRdbStorage和StatisticRdbRepository两个类

**Comment by junyi5257** [comment]
当前版本数据源，默认(仅支持)使用的,就是mysql，估计没时间改这个

**Comment by chenshuangxi** [comment]
> 他们的建表语句的字段两边加了``符号，在Oracle下边就会报错，但是MySql不会，可以通过修改源码解决。位置是JobEventRdbStorage和StatisticRdbRepository两个类

改了源码支持oracle，但是启动一段时间之后，再重启的话，非常慢，60个定时任务，360秒才启动完，我设置的默认启动都是disable的，请问有没有遇到过？

**Comment by terrymanu** [comment]
Please add SQL for oracle dialect. Ref #840
