### ISSUE TITLE
分片执行，偶尔插入执行记录日志（JOB_EXECUTION_LOG）会报Duplicate entry 'xx' for key 'PRIMARY'

### ISSUE THREAD

**Issue by xue2lang** [apache/shardingsphere-elasticjob#601]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
1.0.2
### Expected behavior （您预期的结果是）
正常按照分片项插入执行记录日志
### Actual behavior （实际运行的结果是）

ERROR druid.sql.Statement[152] - {conn-10019, pstmt-20081} execute error. INSERT INTO `JOB_EXECUTION_LOG` (`id`, `job_name`, `task_id`, `hostname`, `ip`, `sharding_item`, `execution_source`, `is_success`, `start_time`, `complete_time`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);

com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'bfc8a2e3-b114-424b-af7a-d49dd328bb4a' for key 'PRIMARY'

### Steps to reproduce the behavior （可重现问题的操作步骤）
本地集群测试环境：10台机器，分20片，采用DataFlow数据流方式处理业务

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
此处无任何重要代码，即任务启动后，偶尔会报此异常

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by gMan1990** [comment]
日志里一大堆。。不知道啥原因，我都没分片，还是simplejob
```text
{conn-10068, pstmt-23148} execute error. INSERT INTO `JOB_EXECUTION_LOG` (`id`, `job_name`, `task_id`, `hostname`, `ip`, `sharding_item`, `execution_source`, `is_success`, `sta
rt_time`, `complete_time`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'cc38d37f-1d28-44f0-bc44-0df7b71c879f' for key 'PRIMARY'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_152]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_152]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_152]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_152]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197) ~[mysql-connector-java-5.1.46.jar:5.1.46]
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3051) ~[druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440) [druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3049) [druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.filter.FilterAdapter.preparedStatement_execute(FilterAdapter.java:1080) [druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3049) [druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:167) [druid-1.1.9.jar:1.1.9]
        at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:498) [druid-1.1.9.jar:1.1.9]
        at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.insertJobExecutionEventWhenSuccess(JobEventRdbStorage.java:233) [elastic-job-common-core-2.1.5.jar:?]
        at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.updateJobExecutionEventWhenSuccess(JobEventRdbStorage.java:206) [elastic-job-common-core-2.1.5.jar:?]
        at com.dangdang.ddframe.job.event.rdb.JobEventRdbStorage.addJobExecutionEvent(JobEventRdbStorage.java:156) [elastic-job-common-core-2.1.5.jar:?]
        at com.dangdang.ddframe.job.event.rdb.JobEventRdbListener.listen(JobEventRdbListener.java:42) [elastic-job-common-core-2.1.5.jar:?]
        at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-23.5-jre.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-23.5-jre.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by gMan1990** [comment]
这个你要看是哪里打印的，我这是[ERROR druid.sql.Statement]，所以不要紧的。
https://github.com/elasticjob/elastic-job-lite/blob/9cc659f8e315e18efa9a3e57f0260fa50f616d17/elastic-job-common/elastic-job-common-core/src/main/java/com/dangdang/ddframe/job/event/rdb/JobEventRdbStorage.java#L235
```java
            if (isDuplicateRecord(ex)) {
                return updateJobExecutionEventWhenSuccess(jobExecutionEvent);
            }
```

**Comment by terrymanu** [comment]
Fixed at 2.x version, please upgrade
