### ISSUE TITLE
事件追踪数据源配置有问题或者没有此数据库时，程序不报错

### ISSUE THREAD

**Issue by EmuuGrass** [apache/shardingsphere-elasticjob#633]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5
### Expected behavior （您预期的结果是）
程序报出相应错误日志或者错误栈
### Actual behavior （实际运行的结果是）
启动时卡主
### Steps to reproduce the behavior （可重现问题的操作步骤）
配置数据源，但是不建立相对应的数据库
### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）
![image](https://user-images.githubusercontent.com/8805039/54411036-d471c300-4728-11e9-9b3c-c88ce619d8ed.png)

![image](https://user-images.githubusercontent.com/8805039/54411168-5a8e0980-4729-11e9-9971-4a3a798b81fc.png)

然后把elastic_job这个库删掉，启动时直接卡住，但是没有相对应的错误日志，排查问题的时候比较难找到原因

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by compilerduck** [comment]
经过验证，应该是可以报出相应错误信息（见下面日志），且启动时也没有被卡住。相关逻辑请参考JobEventBus.register()方法，当数据库不存在时，isRegistered变量不会置为true，后面写库时会先判断isRegistered变量。如果还有问题，请重开本issue。

[ERROR] 2019-10-10 10:09:27,323 --main-- [com.dangdang.ddframe.job.event.JobEventBus] Elastic job: create JobEventListener failure, error is:  
com.dangdang.ddframe.job.event.JobEventListenerConfigurationException: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Unknown database 'elasticjob200')
	at com.dangdang.ddframe.job.event.rdb.JobEventRdbConfiguration.createJobEventListener(JobEventRdbConfiguration.java:48) ~[elastic-job-common-core-2.1.5.jar:na]
	at com.dangdang.ddframe.job.event.JobEventBus.register(JobEventBus.java:57) [elastic-job-common-core-2.1.5.jar:na]
	at com.dangdang.ddframe.job.event.JobEventBus.<init>(JobEventBus.java:52) [elastic-job-common-core-2.1.5.jar:na]
	at com.dangdang.ddframe.job.lite.api.JobScheduler.<init>(JobScheduler.java:79) [elastic-job-lite-core-2.1.5.jar:na]
	at com.dangdang.ddframe.job.lite.spring.api.SpringJobScheduler.<init>(SpringJobScheduler.java:46) [elastic-job-lite-spring-2.1.5.jar:na]
