### ISSUE TITLE
k8s 上部署集群一直 Name or service not known elastic-job-lite v2.1.5

### ISSUE THREAD

**Issue by fanmuyong** [apache/shardingsphere-elasticjob#666]
2019-07-27 11:00:00 [ERROR] [StatisticsStudentCallbackJob_Worker-1] - org.quartz.core.ErrorLogger : Job (DEFAULT.StatisticsStudentCallbackJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.dangdang.ddframe.job.util.env.HostException: java.net.UnknownHostException: statistics-xueguan-task-deploy-77c4b4dc9b-s5877: statistics-xueguan-task-deploy-77c4b4dc9b-s5877: Name or service not known
        at com.dangdang.ddframe.job.util.env.IpUtils.getHostName(IpUtils.java:105)
        at com.dangdang.ddframe.job.event.type.JobExecutionEvent.<init>(JobExecutionEvent.java:43)
        at com.dangdang.ddframe.job.executor.AbstractElasticJobExecutor.process(AbstractElasticJobExecutor.java:170)
        at com.dangdang.ddframe.job.executor.AbstractElasticJobExecutor.execute(AbstractElasticJobExecutor.java:150)
        at com.dangdang.ddframe.job.executor.AbstractElasticJobExecutor.execute(AbstractElasticJobExecutor.java:122)
        at com.dangdang.ddframe.job.lite.internal.schedule.LiteJob.execute(LiteJob.java:26)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 common frames omitted
Caused by: java.net.UnknownHostException: statistics-xueguan-task-deploy-77c4b4dc9b-s5877: statistics-xueguan-task-deploy-77c4b4dc9b-s5877: Name or service not known
        at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
        at com.dangdang.ddframe.job.util.env.IpUtils.getHostName(IpUtils.java:103)
        ... 7 common frames omitted
Caused by: java.net.UnknownHostException: statistics-xueguan-task-deploy-77c4b4dc9b-s5877: Name or service not known
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
        ... 8 common frames omitted

**Comment by compilerduck** [comment]
还能复现吗？感觉像是k8s集群配置的问题？

**Comment by fanmuyong** [comment]
部署上去一直都启动不了，我们换成xxl-job了，运行没问题
