### ISSUE TITLE
一个任务失败导致其他任务全部失效

### ISSUE THREAD

**Issue by purgeyao** [apache/shardingsphere-elasticjob#672]
### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
最新版本

问题：
一个服务有多个任务，第一个任务执行失败了，可能是业务异常。
很奇怪的是后面的任务全部都是这个错误了，去控制台上看发现都失效了。
```
2019-08-29 11:40:00.061 [batch-service_MerchantUnSettlingAmountJob_Worker-1] ERROR org.quartz.core.ErrorLogger - Job (DEFAULT.batch-service_MerchantUnSettlingAmountJob threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.dangdang.ddframe.job.reg.exception.RegException: java.lang.IllegalStateException: instance must be started before calling this method
	at com.dangdang.ddframe.job.reg.exception.RegExceptionHandler.handleException(RegExceptionHandler.java:52)
	at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:162)
	at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:143)
	at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:72)
	at com.dangdang.ddframe.job.lite.internal.config.ConfigurationService.load(ConfigurationService.java:54)
	at com.dangdang.ddframe.job.lite.internal.schedule.LiteJobFacade.loadJobRootConfiguration(LiteJobFacade.java:78)
	at com.dangdang.ddframe.job.lite.internal.schedule.LiteJobFacade.loadJobRootConfiguration(LiteJobFacade.java:49)
	at com.dangdang.ddframe.job.executor.AbstractElasticJobExecutor.(AbstractElasticJobExecutor.java:65)
	at com.dangdang.ddframe.job.executor.type.SimpleJobExecutor.(SimpleJobExecutor.java:35)
	at com.dangdang.ddframe.job.executor.JobExecutorFactory.getJobExecutor(JobExecutorFactory.java:51)
	at com.dangdang.ddframe.job.lite.internal.schedule.LiteJob.execute(LiteJob.java:26)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
Caused by: java.lang.IllegalStateException: instance must be started before calling this method
	at org.apache.curator.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getData(CuratorFrameworkImpl.java:375)
	at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.getDirectly(ZookeeperRegistryCenter.java:158)
	... 11 common frames omitted
```

**Comment by purgeyao** [comment]
@terrymanu 麻烦帮忙看下呗。

**Comment by purgeyao** [comment]
@haocao 麻烦帮忙看下呗

**Comment by glasses1989** [comment]
你这个是zk连接错误，zkclient已经被关闭了

**Comment by purgeyao** [comment]
@glasses1989 一个错误导致springboot容器关闭，导致所有连接池关闭 包括zk 。 问题解决了 谢谢回答
