### ISSUE TITLE
将服务放入阿里云后，部了两台机器，但是只有一台生效，另一台启动后无法运行定时任务

### ISSUE THREAD

**Issue by zhangjs09** [apache/shardingsphere-elasticjob#703]
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Elastic-Job do you using?（您使用的Elastic-Job版本为？）
2.1.5

### Expected behavior （您预期的结果是）
两台机器同时跑elastic-job，并进行平均分片

### Actual behavior （实际运行的结果是）
两台机器只有1台成功运行，另一台处于假死状态，启动后不运行定时任务，请问如何排查这个问题

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/elasticjob/elastic-job-example
（代码请基于 https://github.com/elasticjob/elastic-job-example）

**Comment by Leonidasz** [comment]
You can check the process logic of sharding items on the 'suspended' host. For example, you can stop the 'suspended' node, and confirm whether all sharding items can run normally on one node.
可以确认一下异常主机上对应分片项的作业逻辑是否存在问题，比如可以将异常节点直接停掉，确认下所有的分片项在一台节点上是否能正常运行。

**Comment by zhangjs09** [comment]
请问一下，启动时会报这个错，是这个影响了定时任务吗  
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[na:1.8.0_181]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1476) ~[na:1.8.0_181]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1474) ~[na:1.8.0_181]
        at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.findTreeCache(ZookeeperRegistryCenter.java:147) ~[elastic-job-common-core-2.1.5.jar!/:na]
        at com.dangdang.ddframe.job.reg.zookeeper.ZookeeperRegistryCenter.get(ZookeeperRegistryCenter.java:135) ~[elastic-job-common-core-2.1.5.jar!/:na]
        at com.dangdang.ddframe.job.lite.internal.storage.JobNodeStorage.getJobNodeData(JobNodeStorage.java:72) ~[elastic-job-lite-core-2.1.5.jar!/:na]
        at com.dangdang.ddframe.job.lite.internal.election.LeaderService.isLeader(LeaderService.java:84) ~[elastic-job-lite-core-2.1.5.jar!/:na]
        at com.dangdang.ddframe.job.lite.internal.election.ElectionListenerManager$LeaderAbdicationJobListener.dataChanged(ElectionListenerManager.java:91) ~[elastic-job-lite-core-2.1.5.jar!/:na]
        at com.dangdang.ddframe.job.lite.internal.listener.AbstractJobListener.childEvent(AbstractJobListener.java:44) ~[elastic-job-lite-core-2.1.5.jar!/:na]
        at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:732) [curator-recipes-2.10.0.jar!/:na]
        at org.apache.curator.framework.recipes.cache.TreeCache$2.apply(TreeCache.java:726) [curator-recipes-2.10.0.jar!/:na]
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93) [curator-framework-2.10.0.jar!/:na]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299) [guava-18.0.jar!/:na]
        at org.apache.curator.framework.listen.ListenerContainer.forEach(ListenerContainer.java:85) [curator-framework-2.10.0.jar!/:na]
        at org.apache.curator.framework.recipes.cache.TreeCache.callListeners(TreeCache.java:725) [curator-recipes-2.10.0.jar!/:na]
        at org.apache.curator.framework.recipes.cache.TreeCache.access$1400(TreeCache.java:71) [curator-recipes-2.10.0.jar!/:na]
        at org.apache.curator.framework.recipes.cache.TreeCache$4.run(TreeCache.java:843) [curator-recipes-2.10.0.jar!/:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

**Comment by kekerzzZ** [comment]
@zhangjs09  Hi, this NPE problem due to the use of HashMap in concurrent scenes,  it has been resolved in version 3.x.
