### ISSUE TITLE
Run java example throw event trace data source exception

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere-elasticjob#954]
When running java example, it will throw event trace data source exception.

The main class is `org.apache.shardingsphere.elasticjob.lite.example.JavaMain`

Exception is:

```
[ERROR] 2020-07-05 19:15:40,200 --javaDataflowElasticJob_Worker-1-- [org.apache.shardingsphere.elasticjob.lite.tracing.JobEventBus] Elastic job: create tracing listener failure, error is:  
org.apache.shardingsphere.elasticjob.lite.tracing.exception.TracingConfigurationException: org.h2.jdbc.JdbcSQLException: Table "JOB_EXECUTION_LOG" already exists; SQL statement:
CREATE TABLE JOB_EXECUTION_LOG (id CHARACTER(40) NOT NULL, job_name CHARACTER(100) NOT NULL, task_id CHARACTER(255) NOT NULL, hostname CHARACTER(255) NOT NULL, ip CHARACTER(50) NOT NULL, sharding_item INTEGER NOT NULL, execution_source CHARACTER(20) NOT NULL, failure_cause CHARACTER VARYING(4000) NULL, is_success INTEGER NOT NULL, start_time TIMESTAMP NULL, complete_time TIMESTAMP NULL, PRIMARY KEY (id)) [42101-184]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.listener.RDBTracingListenerConfiguration.createTracingListener(RDBTracingListenerConfiguration.java:37) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.listener.RDBTracingListenerConfiguration.createTracingListener(RDBTracingListenerConfiguration.java:30) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.listener.TracingListenerFactory.getListener(TracingListenerFactory.java:56) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.JobEventBus.register(JobEventBus.java:68) [classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.JobEventBus.<init>(JobEventBus.java:56) [classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJobFacade.<init>(LiteJobFacade.java:71) [classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.executor.ElasticJobExecutor.<init>(ElasticJobExecutor.java:82) [classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.executor.ElasticJobExecutor.<init>(ElasticJobExecutor.java:69) [classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.createExecutor(LiteJob.java:56) [classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.execute(LiteJob.java:52) [classes/:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.2.jar:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Table "JOB_EXECUTION_LOG" already exists; SQL statement:
CREATE TABLE JOB_EXECUTION_LOG (id CHARACTER(40) NOT NULL, job_name CHARACTER(100) NOT NULL, task_id CHARACTER(255) NOT NULL, hostname CHARACTER(255) NOT NULL, ip CHARACTER(50) NOT NULL, sharding_item INTEGER NOT NULL, execution_source CHARACTER(20) NOT NULL, failure_cause CHARACTER VARYING(4000) NULL, is_success INTEGER NOT NULL, start_time TIMESTAMP NULL, complete_time TIMESTAMP NULL, PRIMARY KEY (id)) [42101-184]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.184.jar:1.4.184]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.184.jar:1.4.184]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.184.jar:1.4.184]
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:111) ~[h2-1.4.184.jar:1.4.184]
	at org.h2.command.CommandContainer.update(CommandContainer.java:78) ~[h2-1.4.184.jar:1.4.184]
	at org.h2.command.Command.executeUpdate(Command.java:254) ~[h2-1.4.184.jar:1.4.184]
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:198) ~[h2-1.4.184.jar:1.4.184]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.storage.RDBJobEventStorage.createJobExecutionTable(RDBJobEventStorage.java:132) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.storage.RDBJobEventStorage.createJobExecutionTableAndIndexIfNeeded(RDBJobEventStorage.java:100) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.storage.RDBJobEventStorage.initTablesAndIndexes(RDBJobEventStorage.java:91) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.storage.RDBJobEventStorage.<init>(RDBJobEventStorage.java:74) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.listener.RDBTracingListener.<init>(RDBTracingListener.java:36) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.listener.RDBTracingListenerConfiguration.createTracingListener(RDBTracingListenerConfiguration.java:35) ~[classes/:na]
	... 11 common frames omitted
[ERROR] 2020-07-05 19:15:40,200 --javaSimpleJob_Worker-1-- [org.apache.shardingsphere.elasticjob.lite.tracing.JobEventBus] Elastic job: create tracing listener failure, error is:  
org.apache.shardingsphere.elasticjob.lite.tracing.exception.TracingConfigurationException: org.h2.jdbc.JdbcSQLException: Table "JOB_EXECUTION_LOG" already exists; SQL statement:
CREATE TABLE JOB_EXECUTION_LOG (id CHARACTER(40) NOT NULL, job_name CHARACTER(100) NOT NULL, task_id CHARACTER(255) NOT NULL, hostname CHARACTER(255) NOT NULL, ip CHARACTER(50) NOT NULL, sharding_item INTEGER NOT NULL, execution_source CHARACTER(20) NOT NULL, failure_cause CHARACTER VARYING(4000) NULL, is_success INTEGER NOT NULL, start_time TIMESTAMP NULL, complete_time TIMESTAMP NULL, PRIMARY KEY (id)) [42101-184]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.listener.RDBTracingListenerConfiguration.createTracingListener(RDBTracingListenerConfiguration.java:37) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.listener.RDBTracingListenerConfiguration.createTracingListener(RDBTracingListenerConfiguration.java:30) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.listener.TracingListenerFactory.getListener(TracingListenerFactory.java:56) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.JobEventBus.register(JobEventBus.java:68) [classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.JobEventBus.<init>(JobEventBus.java:56) [classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJobFacade.<init>(LiteJobFacade.java:71) [classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.executor.ElasticJobExecutor.<init>(ElasticJobExecutor.java:82) [classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.executor.ElasticJobExecutor.<init>(ElasticJobExecutor.java:69) [classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.createExecutor(LiteJob.java:56) [classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.internal.schedule.LiteJob.execute(LiteJob.java:52) [classes/:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.2.jar:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: Table "JOB_EXECUTION_LOG" already exists; SQL statement:
CREATE TABLE JOB_EXECUTION_LOG (id CHARACTER(40) NOT NULL, job_name CHARACTER(100) NOT NULL, task_id CHARACTER(255) NOT NULL, hostname CHARACTER(255) NOT NULL, ip CHARACTER(50) NOT NULL, sharding_item INTEGER NOT NULL, execution_source CHARACTER(20) NOT NULL, failure_cause CHARACTER VARYING(4000) NULL, is_success INTEGER NOT NULL, start_time TIMESTAMP NULL, complete_time TIMESTAMP NULL, PRIMARY KEY (id)) [42101-184]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345) ~[h2-1.4.184.jar:1.4.184]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.184.jar:1.4.184]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.184.jar:1.4.184]
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:111) ~[h2-1.4.184.jar:1.4.184]
	at org.h2.command.CommandContainer.update(CommandContainer.java:78) ~[h2-1.4.184.jar:1.4.184]
	at org.h2.command.Command.executeUpdate(Command.java:254) ~[h2-1.4.184.jar:1.4.184]
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:198) ~[h2-1.4.184.jar:1.4.184]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.storage.RDBJobEventStorage.createJobExecutionTable(RDBJobEventStorage.java:132) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.storage.RDBJobEventStorage.createJobExecutionTableAndIndexIfNeeded(RDBJobEventStorage.java:100) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.storage.RDBJobEventStorage.initTablesAndIndexes(RDBJobEventStorage.java:91) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.storage.RDBJobEventStorage.<init>(RDBJobEventStorage.java:74) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.listener.RDBTracingListener.<init>(RDBTracingListener.java:36) ~[classes/:na]
	at org.apache.shardingsphere.elasticjob.lite.tracing.rdb.listener.RDBTracingListenerConfiguration.createTracingListener(RDBTracingListenerConfiguration.java:35) ~[classes/:na]
	... 11 common frames omitted
```

**Comment by rudy2steiner** [comment]
Please assign to me!

**Comment by terrymanu** [comment]
@rudy2steiner, Thank you, assigned
